-- THE BLOOD FONT DRINKS BACK (owner 2026-09-29: "the blood font should cast something on you if you use it aka
-- drink the blood"). A targeted patch of ONLY the Blood Font (901310), cut from lore-factions.sql (generated by
-- lore_factions.py, which now carries the same rows): re-applying the whole faction file would also undo
-- art2-sounds.sql's live sound-table change on the Blood-Sister and the Deru-Bound Keeper.
--
-- Use -> InqQuest BloodFontDrink. Off its 10-minute timer the font stamps it and casts on you: Harm Other IV (the
-- price, a curse like any other: resisted on a roll against the font's ItemSpellcraft 300), then Regeneration
-- Other VI and Strength Other VI. On the timer it lies still. Re-runnable.
--
-- Apply: ssh gpubox '~/Dereth-Unity/tools/gpubox-ace/apply-live.sh tools/gpubox-ace/blood-font-drink.sql 0E49'
START TRANSACTION;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 901310;
DELETE FROM weenie_properties_emote WHERE object_Id = 901310;
DELETE FROM weenie_properties_int WHERE object_Id = 901310 AND type = 16; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901310, 16, 32);
DELETE FROM weenie_properties_int WHERE object_Id = 901310 AND type = 106; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901310, 106, 300);
DELETE FROM weenie_properties_float WHERE object_Id = 901310 AND type = 54; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901310, 54, 3.0);
DELETE FROM quest WHERE name = 'BloodFontDrink';
INSERT INTO quest (name, min_Delta, max_Solves, message) VALUES ('BloodFontDrink', 600, -1, 'Drank from the Blood Font (once every 10 minutes)');
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (901310, 7, 1, NULL);
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 21, 0, 1, 'BloodFontDrink');
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (901310, 12, 1, 'BloodFontDrink');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 18, 0, 1, 'The font lies still. It has taken enough of you for now.');
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (901310, 13, 1, 'BloodFontDrink');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 22, 0, 1, 'BloodFontDrink');
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 1, 18, 0, 1, 'You cup your hands and drink from the Blood Font. It is warm, and it drinks from you in turn.');
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, p_Script) VALUES (@e, 2, 7, 0, 1, 32);
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, spell_Id) VALUES (@e, 3, 19, 0, 1, 1174);
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, spell_Id) VALUES (@e, 4, 19, 0, 1, 164);
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, spell_Id) VALUES (@e, 5, 19, 0, 1, 1337);
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 6, 18, 0, 1, 'The blood burns in you. The Warden remembers every pint.');
COMMIT;
