-- THE DEV VAULT (owner 2026-09-30): "I want to see them to judge if there is anything we can use that the
-- devs started but never finished." Five free vendors in admin-only Hotel Swank selling every item of the
-- 2026-09-30 obtainable-items audit in category "no-wiki-record" (dev, NPC-only, unreleased or unverifiable),
-- split by ItemType. Everything costs 1 pyreal (SellPrice 0: ACE charges max(1, ...), Vendor.GetSellCost),
-- and the vendors buy nothing (MerchandiseItemTypes 0), so a free dev item cannot be sold back to them.
-- Service items (ItemType Service: vendor buff services, not things to hold) are left out.
--
-- GENERATED by tools/gpubox-ace/gen_dev_vault.py from docs/OBTAINABLE-ITEMS-2026-09-30-unreachable.tsv.
-- Edit the generator, not this file. docs/DEV-VAULT.md.
--
-- Where: the lifestone room of Hotel Swank (0x018A, cell 0x018A0289, the room east of the Jeeves room),
--   a row on its north wall at y -76.4, facing south. Swank is admin-only (docs/SWANK-AND-TOUR-2026-09-27.md s9).
--   901600 Dev Vault Weapons (guid 0x7018A4E1, x 126.8): melee weapons and casters (ItemType MeleeWeapon, Caster); look cloned from retail 24220
--   901601 Dev Vault Missiles (guid 0x7018A4E2, x 128.4): bows, crossbows, atlatls, thrown weapons and ammunition (MissileWeapon); look cloned from retail 651
--   901602 Dev Vault Armour (guid 0x7018A4E3, x 130.0): armour, clothing and jewelry (Armor, Clothing, Jewelry); look cloned from retail 975
--   901603 Dev Vault Portal Gems (guid 0x7018A4E4, x 131.6): portal and sending gems (Gem named Portal or Sending); look cloned from retail 26694
--   901604 Dev Vault Curios (guid 0x7018A4E5, x 133.2): everything else: books and notes, misc, other gems, keys, food, tinkering, containers; look cloned from retail 2500
--
-- IDEMPOTENT: deletes weenies 901600-901604, their shop rows and instances first.
-- Apply: ssh gpubox '~/Dereth-Unity/tools/gpubox-ace/apply-live.sh tools/gpubox-ace/dev-vault-vendors.sql 018A'
-- Undo:  DELETE FROM landblock_instance WHERE guid IN (0x7018A4E1, 0x7018A4E2, 0x7018A4E3, 0x7018A4E4, 0x7018A4E5); then the DELETE block below.
START TRANSACTION;
DELETE FROM landblock_instance WHERE guid IN (0x7018A4E1, 0x7018A4E2, 0x7018A4E3, 0x7018A4E4, 0x7018A4E5) OR weenie_Class_Id BETWEEN 901600 AND 901604;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_int WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_int64 WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_bool WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_float WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_string WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_d_i_d WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_i_i_d WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_attribute WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_skill WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_body_part WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_palette WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_texture_map WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_anim_part WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_spell_book WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_event_filter WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_create_list WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_generator WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_position WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie_properties_emote WHERE object_Id BETWEEN 901600 AND 901604;
DELETE FROM weenie WHERE class_Id BETWEEN 901600 AND 901604;

-- 901600 Dev Vault Weapons: clone of 24220
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901600, 'devvaultweapons', type FROM weenie WHERE class_Id = 24220;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901600, type, value FROM weenie_properties_int WHERE object_Id = 24220;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901600, type, value FROM weenie_properties_int64 WHERE object_Id = 24220;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901600, type, value FROM weenie_properties_bool WHERE object_Id = 24220;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901600, type, value FROM weenie_properties_float WHERE object_Id = 24220;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901600, type, value FROM weenie_properties_string WHERE object_Id = 24220;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901600, type, value FROM weenie_properties_d_i_d WHERE object_Id = 24220;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901600, type, value FROM weenie_properties_i_i_d WHERE object_Id = 24220;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901600, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 24220;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901600, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 24220;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901600, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 24220;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901600, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 24220;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901600, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 24220;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901600, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 24220;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 901600, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 24220;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901600, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 24220;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901600, event FROM weenie_properties_event_filter WHERE object_Id = 24220;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) SELECT 901600, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond FROM weenie_properties_create_list WHERE object_Id = 24220 AND destination_Type = 2;
DELETE FROM weenie_properties_string WHERE object_Id = 901600 AND type IN (1, 5, 16, 24);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901600, 1, 'Dev Vault Weapons'), (901600, 5, 'Dev Vault'), (901600, 16, 'Admin only. Sells, for one pyreal each, items that exist in the data with no record of a player ever having them: dev, NPC-only, unreleased or unverifiable. Melee weapons and casters (ItemType MeleeWeapon, Caster). Buys nothing.');
DELETE FROM weenie_properties_int WHERE object_Id = 901600 AND type = 74;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901600, 74, 0);
DELETE FROM weenie_properties_float WHERE object_Id = 901600 AND type = 38;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901600, 38, 0);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901600 AND type = 57;

-- 901601 Dev Vault Missiles: clone of 651
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901601, 'devvaultmissiles', type FROM weenie WHERE class_Id = 651;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901601, type, value FROM weenie_properties_int WHERE object_Id = 651;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901601, type, value FROM weenie_properties_int64 WHERE object_Id = 651;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901601, type, value FROM weenie_properties_bool WHERE object_Id = 651;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901601, type, value FROM weenie_properties_float WHERE object_Id = 651;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901601, type, value FROM weenie_properties_string WHERE object_Id = 651;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901601, type, value FROM weenie_properties_d_i_d WHERE object_Id = 651;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901601, type, value FROM weenie_properties_i_i_d WHERE object_Id = 651;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901601, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 651;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901601, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 651;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901601, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 651;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901601, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 651;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901601, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 651;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901601, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 651;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 901601, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 651;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901601, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 651;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901601, event FROM weenie_properties_event_filter WHERE object_Id = 651;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) SELECT 901601, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond FROM weenie_properties_create_list WHERE object_Id = 651 AND destination_Type = 2;
DELETE FROM weenie_properties_string WHERE object_Id = 901601 AND type IN (1, 5, 16, 24);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901601, 1, 'Dev Vault Missiles'), (901601, 5, 'Dev Vault'), (901601, 16, 'Admin only. Sells, for one pyreal each, items that exist in the data with no record of a player ever having them: dev, NPC-only, unreleased or unverifiable. Bows, crossbows, atlatls, thrown weapons and ammunition (MissileWeapon). Buys nothing.');
DELETE FROM weenie_properties_int WHERE object_Id = 901601 AND type = 74;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901601, 74, 0);
DELETE FROM weenie_properties_float WHERE object_Id = 901601 AND type = 38;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901601, 38, 0);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901601 AND type = 57;

-- 901602 Dev Vault Armour: clone of 975
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901602, 'devvaultarmour', type FROM weenie WHERE class_Id = 975;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901602, type, value FROM weenie_properties_int WHERE object_Id = 975;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901602, type, value FROM weenie_properties_int64 WHERE object_Id = 975;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901602, type, value FROM weenie_properties_bool WHERE object_Id = 975;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901602, type, value FROM weenie_properties_float WHERE object_Id = 975;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901602, type, value FROM weenie_properties_string WHERE object_Id = 975;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901602, type, value FROM weenie_properties_d_i_d WHERE object_Id = 975;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901602, type, value FROM weenie_properties_i_i_d WHERE object_Id = 975;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901602, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 975;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901602, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 975;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901602, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 975;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901602, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 975;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901602, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 975;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901602, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 975;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 901602, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 975;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901602, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 975;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901602, event FROM weenie_properties_event_filter WHERE object_Id = 975;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) SELECT 901602, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond FROM weenie_properties_create_list WHERE object_Id = 975 AND destination_Type = 2;
DELETE FROM weenie_properties_string WHERE object_Id = 901602 AND type IN (1, 5, 16, 24);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901602, 1, 'Dev Vault Armour'), (901602, 5, 'Dev Vault'), (901602, 16, 'Admin only. Sells, for one pyreal each, items that exist in the data with no record of a player ever having them: dev, NPC-only, unreleased or unverifiable. Armour, clothing and jewelry (Armor, Clothing, Jewelry). Buys nothing.');
DELETE FROM weenie_properties_int WHERE object_Id = 901602 AND type = 74;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901602, 74, 0);
DELETE FROM weenie_properties_float WHERE object_Id = 901602 AND type = 38;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901602, 38, 0);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901602 AND type = 57;

-- 901603 Dev Vault Portal Gems: clone of 26694
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901603, 'devvaultportalgems', type FROM weenie WHERE class_Id = 26694;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901603, type, value FROM weenie_properties_int WHERE object_Id = 26694;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901603, type, value FROM weenie_properties_int64 WHERE object_Id = 26694;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901603, type, value FROM weenie_properties_bool WHERE object_Id = 26694;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901603, type, value FROM weenie_properties_float WHERE object_Id = 26694;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901603, type, value FROM weenie_properties_string WHERE object_Id = 26694;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901603, type, value FROM weenie_properties_d_i_d WHERE object_Id = 26694;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901603, type, value FROM weenie_properties_i_i_d WHERE object_Id = 26694;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901603, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 26694;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901603, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 26694;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901603, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 26694;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901603, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 26694;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901603, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 26694;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901603, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 26694;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 901603, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 26694;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901603, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 26694;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901603, event FROM weenie_properties_event_filter WHERE object_Id = 26694;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) SELECT 901603, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond FROM weenie_properties_create_list WHERE object_Id = 26694 AND destination_Type = 2;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (901603, 2, 12310, 0, 0, 0, 0);
DELETE FROM weenie_properties_string WHERE object_Id = 901603 AND type IN (1, 5, 16, 24);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901603, 1, 'Dev Vault Portal Gems'), (901603, 5, 'Dev Vault'), (901603, 16, 'Admin only. Sells, for one pyreal each, items that exist in the data with no record of a player ever having them: dev, NPC-only, unreleased or unverifiable. Portal and sending gems (Gem named Portal or Sending). Buys nothing.');
DELETE FROM weenie_properties_int WHERE object_Id = 901603 AND type = 74;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901603, 74, 0);
DELETE FROM weenie_properties_float WHERE object_Id = 901603 AND type = 38;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901603, 38, 0);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901603 AND type = 57;

-- 901604 Dev Vault Curios: clone of 2500
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901604, 'devvaultcurios', type FROM weenie WHERE class_Id = 2500;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901604, type, value FROM weenie_properties_int WHERE object_Id = 2500;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901604, type, value FROM weenie_properties_int64 WHERE object_Id = 2500;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901604, type, value FROM weenie_properties_bool WHERE object_Id = 2500;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901604, type, value FROM weenie_properties_float WHERE object_Id = 2500;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901604, type, value FROM weenie_properties_string WHERE object_Id = 2500;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901604, type, value FROM weenie_properties_d_i_d WHERE object_Id = 2500;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901604, type, value FROM weenie_properties_i_i_d WHERE object_Id = 2500;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901604, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 2500;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901604, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 2500;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901604, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 2500;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901604, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 2500;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901604, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 2500;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901604, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 2500;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 901604, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 2500;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901604, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 2500;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901604, event FROM weenie_properties_event_filter WHERE object_Id = 2500;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) SELECT 901604, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond FROM weenie_properties_create_list WHERE object_Id = 2500 AND destination_Type = 2;
DELETE FROM weenie_properties_string WHERE object_Id = 901604 AND type IN (1, 5, 16, 24);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901604, 1, 'Dev Vault Curios'), (901604, 5, 'Dev Vault'), (901604, 16, 'Admin only. Sells, for one pyreal each, items that exist in the data with no record of a player ever having them: dev, NPC-only, unreleased or unverifiable. Everything else: books and notes, misc, other gems, keys, food, tinkering, containers. Buys nothing.');
DELETE FROM weenie_properties_int WHERE object_Id = 901604 AND type = 74;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901604, 74, 0);
DELETE FROM weenie_properties_float WHERE object_Id = 901604 AND type = 38;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901604, 38, 0);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901604 AND type = 57;

-- The audit's no-wiki-record items (1451).
DROP TEMPORARY TABLE IF EXISTS dev_vault_items;
CREATE TEMPORARY TABLE dev_vault_items (wcid INT UNSIGNED PRIMARY KEY);
INSERT INTO dev_vault_items VALUES (125), (155), (156), (164), (170), (172), (175), (271), (275), (281), (366), (1440), (1441), (1442), (1444), (1453), (1454), (1455), (1456), (1458), (1482), (1516), (1527), (1528), (1529), (1530), (1541), (1952), (2020), (2021), (2022), (2023), (2025), (2027), (2028), (2029), (2030), (2033), (2034), (2035);
INSERT INTO dev_vault_items VALUES (2036), (2037), (2038), (2039), (2050), (2051), (2052), (2054), (2056), (2057), (2058), (2060), (2061), (2062), (2063), (2158), (2159), (2160), (2161), (2162), (2163), (2164), (2165), (2166), (2167), (2197), (2475), (2476), (2478), (3593), (3653), (3655), (3656), (3714), (3770), (3771), (3772), (3782), (3783), (3784);
INSERT INTO dev_vault_items VALUES (3785), (3790), (3792), (3793), (3799), (3801), (3861), (3862), (3863), (3864), (3941), (4137), (4138), (4184), (4189), (4588), (4591), (4594), (4799), (4800), (4801), (4804), (4914), (4916), (4983), (4990), (5009), (5013), (5028), (5187), (5209), (5327), (5335), (5358), (5409), (5410), (5411), (5412), (5532), (5553);
INSERT INTO dev_vault_items VALUES (5554), (5555), (5558), (5559), (5560), (5561), (5568), (5570), (5571), (5574), (5576), (5578), (5579), (5580), (5581), (5588), (5592), (5593), (5594), (5733), (5734), (5735), (5736), (5737), (5738), (5739), (5740), (5741), (5742), (5743), (5744), (5745), (5746), (5747), (5871), (6116), (6383), (6424), (6440), (6782);
INSERT INTO dev_vault_items VALUES (7313), (7799), (7912), (7913), (7933), (8130), (8132), (8156), (8157), (8158), (8159), (8160), (8161), (8162), (8163), (8164), (8165), (8166), (8167), (8525), (8619), (8622), (8790), (8791), (8792), (8798), (8840), (8867), (8868), (9148), (9181), (9355), (9356), (9550), (9551), (9552), (9553), (9554), (9555), (9556);
INSERT INTO dev_vault_items VALUES (9557), (9558), (9559), (9560), (9561), (10697), (10756), (10920), (11002), (11003), (11004), (11011), (11672), (11674), (11731), (11736), (11840), (11867), (11868), (12003), (12049), (12181), (12182), (12183), (12184), (12199), (12259), (12260), (12275), (12276), (12309), (12310), (12465), (13198), (14590), (14798), (14862), (14863), (14933), (15297);
INSERT INTO dev_vault_items VALUES (19219), (19221), (19223), (19225), (19227), (19229), (19231), (19233), (19235), (19237), (19239), (19241), (19243), (19245), (19247), (19481), (19485), (19486), (19487), (19488), (19489), (19490), (19493), (19494), (19495), (19496), (19497), (19498), (19499), (19500), (19501), (19502), (19504), (19505), (19506), (19508), (19509), (19510), (19511), (19512);
INSERT INTO dev_vault_items VALUES (19517), (19518), (19520), (19521), (19522), (19524), (19525), (19526), (19527), (19528), (19529), (19531), (19532), (19762), (19763), (19764), (19765), (19766), (19767), (19768), (19769), (19770), (19771), (19781), (19782), (19783), (19784), (19785), (19786), (19787), (19788), (19798), (19799), (19800), (19801), (19802), (19803), (19804), (19805), (19806);
INSERT INTO dev_vault_items VALUES (19807), (19817), (19818), (19819), (19820), (19821), (19822), (19823), (19824), (19825), (19826), (19827), (19828), (19829), (19830), (19831), (19832), (19833), (19834), (19835), (19836), (19837), (19838), (19839), (19840), (19841), (19842), (19843), (19853), (19854), (19855), (19856), (19857), (19858), (19859), (19860), (19861), (19862), (19863), (19864);
INSERT INTO dev_vault_items VALUES (19865), (19866), (19867), (19868), (19869), (19870), (19871), (19872), (19873), (19874), (19875), (19876), (19877), (19878), (19879), (19889), (19890), (19891), (19892), (19893), (19894), (19895), (19896), (19898), (19899), (19900), (19901), (19902), (19903), (19904), (19905), (19906), (19907), (19908), (19909), (19910), (19911), (19912), (19913), (19914);
INSERT INTO dev_vault_items VALUES (19915), (19925), (19926), (19927), (19928), (19929), (19930), (19931), (19932), (19933), (19934), (19935), (19936), (19937), (19938), (19939), (19940), (19941), (19942), (19943), (19944), (19945), (19946), (19947), (19948), (19949), (19950), (19951), (19961), (19962), (19963), (19964), (19965), (19966), (19967), (19968), (19969), (19970), (19971), (19972);
INSERT INTO dev_vault_items VALUES (19973), (19974), (19975), (19976), (19977), (19978), (19979), (19980), (19981), (19982), (19983), (19984), (19985), (19986), (19987), (19997), (19998), (19999), (20000), (20001), (20002), (20003), (20004), (20005), (20006), (20007), (20008), (20009), (20010), (20011), (20012), (20013), (20034), (20035), (20036), (20037), (20038), (20039), (20040), (20041);
INSERT INTO dev_vault_items VALUES (20042), (20043), (20053), (20054), (20055), (20056), (20057), (20058), (20059), (20060), (20061), (20062), (20063), (20064), (20065), (20066), (20067), (20068), (20069), (20070), (20071), (20072), (20073), (20074), (20075), (20076), (20077), (20078), (20079), (20089), (20090), (20091), (20092), (20093), (20094), (20095), (20096), (20097), (20098), (20099);
INSERT INTO dev_vault_items VALUES (20100), (20101), (20102), (20103), (20104), (20105), (20106), (20107), (20108), (20109), (20110), (20111), (20112), (20113), (20114), (20115), (20125), (20126), (20127), (20128), (20129), (20130), (20131), (20132), (20142), (20143), (20144), (20145), (20146), (20147), (20148), (20149), (20150), (20151), (20161), (20162), (20163), (20164), (20165), (20166);
INSERT INTO dev_vault_items VALUES (20167), (20168), (20169), (20170), (20171), (20172), (20173), (20174), (20175), (20176), (20177), (20183), (20645), (20927), (20929), (20931), (20933), (20934), (20935), (20937), (20939), (20941), (20942), (20943), (20945), (20946), (20947), (20949), (20950), (20951), (20953), (20954), (20956), (20992), (21018), (21020), (21021), (21022), (21024), (21025);
INSERT INTO dev_vault_items VALUES (21026), (21028), (21030), (21032), (21033), (21035), (21036), (21046), (21047), (21051), (21052), (21057), (21063), (21064), (21067), (21068), (21072), (21074), (21075), (21076), (21080), (21081), (21082), (21083), (21084), (21085), (21087), (21448), (21483), (22218), (22255), (22433), (22434), (22435), (22436), (22437), (22438), (22439), (22541), (22542);
INSERT INTO dev_vault_items VALUES (22543), (22544), (22545), (22743), (22744), (22813), (23109), (23140), (23141), (23142), (23143), (23270), (23308), (23309), (23310), (23311), (23330), (23341), (23370), (23371), (23372), (23373), (23374), (23375), (23376), (23377), (23378), (23379), (23380), (23381), (23382), (23383), (23384), (23385), (23386), (23387), (23388), (23389), (23390), (23391);
INSERT INTO dev_vault_items VALUES (23392), (23393), (23394), (23395), (23396), (23397), (23398), (23399), (23400), (23401), (23402), (23403), (23404), (23405), (23406), (23407), (23408), (23409), (23410), (23411), (23412), (23413), (23414), (23415), (23416), (23417), (23418), (23419), (23420), (23421), (23422), (23423), (23424), (23425), (23426), (23427), (23428), (23429), (23430), (23431);
INSERT INTO dev_vault_items VALUES (23432), (23433), (23434), (23435), (23436), (23437), (23438), (23439), (23440), (23441), (23442), (23443), (23444), (23445), (23446), (23447), (23448), (23449), (23450), (23451), (23452), (23453), (23454), (23455), (23456), (23457), (23458), (23459), (23460), (23461), (23462), (23463), (23464), (23465), (23466), (23469), (23473), (23474), (23475), (23476);
INSERT INTO dev_vault_items VALUES (23518), (23778), (23779), (23780), (23783), (23786), (23787), (23790), (23793), (23794), (23797), (23798), (23799), (23801), (23803), (23804), (23805), (23807), (23808), (23809), (23811), (23812), (23814), (23815), (23816), (23818), (23819), (23820), (23821), (23822), (23823), (23824), (23825), (23826), (23827), (23829), (23830), (23831), (23832), (23833);
INSERT INTO dev_vault_items VALUES (23834), (23835), (23836), (23837), (23838), (23839), (23840), (23841), (23842), (23844), (23845), (23847), (23848), (24066), (24264), (24265), (24266), (24267), (24268), (24945), (24947), (24948), (24949), (24950), (24956), (25280), (25294), (25295), (25296), (25297), (25298), (25299), (25300), (25301), (25302), (25303), (25304), (25305), (25306), (25307);
INSERT INTO dev_vault_items VALUES (25308), (25309), (25310), (25311), (25312), (25515), (25517), (25521), (25729), (25777), (25778), (26010), (26027), (26028), (26029), (26030), (26035), (26036), (26037), (26038), (26057), (26058), (26059), (26060), (26061), (26062), (26063), (26064), (26065), (26066), (26067), (26068), (26069), (26070), (26071), (26072), (26073), (26074), (26075), (26076);
INSERT INTO dev_vault_items VALUES (26077), (26078), (26079), (26080), (26081), (26082), (26083), (26084), (26085), (26086), (26087), (26088), (26089), (26090), (26091), (26092), (26093), (26094), (26095), (26096), (26097), (26098), (26099), (26100), (26101), (26102), (26103), (26104), (26105), (26106), (26107), (26108), (26109), (26110), (26111), (26112), (26113), (26114), (26115), (26116);
INSERT INTO dev_vault_items VALUES (26117), (26118), (26119), (26120), (26121), (26122), (26123), (26124), (26125), (26126), (26127), (26128), (26129), (26130), (26131), (26132), (26133), (26134), (26135), (26136), (26137), (26138), (26139), (26140), (26141), (26142), (26143), (26144), (26145), (26146), (26147), (26148), (26149), (26150), (26151), (26152), (26153), (26154), (26155), (26156);
INSERT INTO dev_vault_items VALUES (26157), (26158), (26159), (26160), (26161), (26162), (26163), (26164), (26165), (26166), (26167), (26168), (26169), (26170), (26171), (26172), (26173), (26174), (26175), (26176), (26177), (26178), (26179), (26180), (26181), (26182), (26183), (26184), (26185), (26186), (26187), (26188), (26189), (26190), (26191), (26192), (26193), (26194), (26195), (26196);
INSERT INTO dev_vault_items VALUES (26197), (26198), (26199), (26200), (26201), (26202), (26203), (26204), (26205), (26206), (26207), (26208), (26209), (26210), (26211), (26212), (26213), (26214), (26215), (26216), (26217), (26218), (26219), (26220), (26221), (26222), (26223), (26224), (26225), (26226), (26227), (26228), (26229), (26230), (26231), (26232), (26233), (26234), (26235), (26236);
INSERT INTO dev_vault_items VALUES (26237), (26238), (26239), (26240), (26241), (26242), (26243), (26244), (26245), (26246), (26247), (26248), (26249), (26250), (26251), (26252), (26253), (26254), (26255), (26256), (26257), (26258), (26259), (26260), (26261), (26262), (26263), (26264), (26265), (26266), (26267), (26268), (26269), (26270), (26271), (26272), (26273), (26274), (26275), (26276);
INSERT INTO dev_vault_items VALUES (26277), (26278), (26279), (26280), (26281), (26282), (26283), (26284), (26285), (26286), (26287), (26288), (26289), (26290), (26291), (26292), (26293), (26294), (26295), (26296), (26297), (26298), (26299), (26300), (26301), (26302), (26303), (26304), (26305), (26306), (26307), (26308), (26309), (26310), (26311), (26312), (26313), (26314), (26315), (26316);
INSERT INTO dev_vault_items VALUES (26317), (26318), (26319), (26320), (26321), (26322), (26323), (26324), (26325), (26326), (26327), (26328), (26329), (26330), (26331), (26332), (26333), (26334), (26335), (26336), (26337), (26338), (26339), (26340), (26341), (26342), (26343), (26344), (26345), (26346), (26347), (26348), (26349), (26350), (26351), (26352), (26353), (26354), (26355), (26356);
INSERT INTO dev_vault_items VALUES (26357), (26358), (26359), (26360), (26361), (26362), (26363), (26364), (26365), (26366), (26367), (26368), (26369), (26370), (26371), (26372), (26373), (26374), (26375), (26376), (26377), (26378), (26379), (26380), (26381), (26382), (26383), (26384), (26385), (26386), (26387), (26388), (26389), (26390), (26391), (26392), (26393), (26394), (26395), (26396);
INSERT INTO dev_vault_items VALUES (26397), (26398), (26399), (26400), (26401), (26402), (26403), (26404), (26405), (26406), (26407), (26408), (26409), (26410), (26411), (26412), (26413), (26414), (26415), (26416), (26417), (26418), (26419), (26420), (26421), (26422), (26423), (26424), (26425), (26426), (26427), (26428), (26429), (26430), (26431), (26432), (26433), (26434), (26435), (26436);
INSERT INTO dev_vault_items VALUES (26437), (26438), (26439), (26440), (26441), (26442), (26443), (26444), (26445), (26446), (26447), (26448), (26449), (26450), (26451), (26636), (26637), (26638), (27122), (27124), (27389), (27393), (27395), (27881), (27882), (27883), (27884), (27885), (27886), (27887), (28107), (28108), (28109), (28110), (28113), (28116), (28117), (28118), (28221), (28222);
INSERT INTO dev_vault_items VALUES (28223), (28224), (28225), (28226), (28227), (28228), (28229), (28230), (28231), (28232), (28233), (28234), (28235), (28236), (28237), (28238), (28239), (28240), (28241), (28619), (28631), (28724), (28743), (28749), (28750), (28751), (28841), (28870), (29115), (29121), (29137), (29150), (29156), (29171), (29215), (29218), (29219), (29220), (29281), (29441);
INSERT INTO dev_vault_items VALUES (29442), (29443), (29448), (29803), (29804), (29805), (29807), (29808), (29809), (29942), (29943), (29944), (29945), (29946), (29947), (29948), (29949), (29950), (29951), (29952), (29953), (29954), (29955), (30402), (30538), (30699), (30919), (30973), (30982), (31041), (31067), (31068), (31069), (31070), (31071), (31072), (31073), (31074), (31075), (31076);
INSERT INTO dev_vault_items VALUES (31077), (31078), (31079), (31080), (31081), (31082), (31083), (31084), (31085), (31086), (31087), (31088), (31089), (31090), (31091), (31160), (31161), (31162), (31177), (31178), (31179), (31180), (31238), (32489), (33459), (35672), (35955), (38323), (38851), (38852), (38853), (38855), (41858), (41859), (45114), (45115), (45116), (45117), (46364), (46365);
INSERT INTO dev_vault_items VALUES (46366), (46367), (46368), (46369), (46370), (46371), (46372), (46373), (46374), (46375), (46389), (46630), (46631), (46632), (46634), (46635), (46636), (46646), (46647), (46648), (47223), (48770), (51833), (51898), (52029), (52030), (52514), (52635), (52636), (69983), (69985), (69987), (69989), (69991), (69992), (69995), (71082), (71356), (71746), (72284);
INSERT INTO dev_vault_items VALUES (72575), (72591), (72592), (72686), (72994), (80226), (87188), (87570), (90111), (90118), (90119);
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond)
SELECT CASE
         WHEN it & 32769 THEN 901600
         WHEN it & 256 THEN 901601
         WHEN it & 14 THEN 901602
         WHEN it & 2048 AND (nm LIKE '%Portal%' OR nm LIKE '%Sending%') THEN 901603
         ELSE 901604 END, 4, wcid, -1, 0, 0, 0
FROM (SELECT d.wcid, COALESCE((SELECT value FROM weenie_properties_int p WHERE p.object_Id = d.wcid AND p.type = 1), 0) it, COALESCE((SELECT value FROM weenie_properties_string s WHERE s.object_Id = d.wcid AND s.type = 1), '') nm
      FROM dev_vault_items d JOIN weenie w ON w.class_Id = d.wcid) x
WHERE (it & 1048576) = 0 AND nm <> ''
ORDER BY 1, nm, wcid;
DROP TEMPORARY TABLE dev_vault_items;

INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES
  (0x7018A4E1, 901600, 0x018A0289, 126.8, -76.4, 0.005, 0, 0, 0, 1, 0),
  (0x7018A4E2, 901601, 0x018A0289, 128.4, -76.4, 0.005, 0, 0, 0, 1, 0),
  (0x7018A4E3, 901602, 0x018A0289, 130.0, -76.4, 0.005, 0, 0, 0, 1, 0),
  (0x7018A4E4, 901603, 0x018A0289, 131.6, -76.4, 0.005, 0, 0, 0, 1, 0),
  (0x7018A4E5, 901604, 0x018A0289, 133.2, -76.4, 0.005, 0, 0, 0, 1, 0);
COMMIT;
