-- RAND'S FESTIVAL SCARECROWS (owner 2026-09-30: "fix it"). Makes KillTaskMGHVScarecrows countable.
-- GENERATED by tools/gpubox-ace/gen_festival_scarecrows.py; edit the generator. docs/FESTIVAL-SCARECROWS.md.
--  1. KillQuest2 (49) = KillTaskMGHVScarecrows on retail 28881 Vile, 28880 Vicious, 28882 Villainous Scarecrow.
--  2. 901605 Mid Scarecrow Gen: clone of retail 73260 lowscarecrowgen (GeneratorEvent EventFallFestival).
--  3. 901605 nested in 7 landscape tables, a slice of up to 0.006 right after the Pumpkin Lord generator.
-- IDEMPOTENT. Apply: ssh gpubox '~/Dereth-Unity/tools/gpubox-ace/apply-live.sh tools/gpubox-ace/festival-scarecrows.sql'
-- Undo: restore the backup apply-live.sh names (gunzip -c <file> | sudo -n mysql ace_world).
START TRANSACTION;

-- 1. the kill counter
DELETE FROM weenie_properties_string WHERE object_Id IN (28881,28880,28882) AND type = 49;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (28881, 49, 'KillTaskMGHVScarecrows'), (28880, 49, 'KillTaskMGHVScarecrows'), (28882, 49, 'KillTaskMGHVScarecrows');

-- 2. the generator: 73260 with a new name and the L70-85 trio
DELETE FROM weenie_properties_generator WHERE object_Id = 901605;
DELETE FROM weenie_properties_int WHERE object_Id = 901605;
DELETE FROM weenie_properties_int64 WHERE object_Id = 901605;
DELETE FROM weenie_properties_bool WHERE object_Id = 901605;
DELETE FROM weenie_properties_float WHERE object_Id = 901605;
DELETE FROM weenie_properties_string WHERE object_Id = 901605;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901605;
DELETE FROM weenie_properties_i_i_d WHERE object_Id = 901605;
DELETE FROM weenie WHERE class_Id = 901605;
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901605, 'ace901605-midscarecrowgen', type FROM weenie WHERE class_Id = 73260;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901605, type, value FROM weenie_properties_int WHERE object_Id = 73260;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901605, type, value FROM weenie_properties_int64 WHERE object_Id = 73260;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901605, type, value FROM weenie_properties_bool WHERE object_Id = 73260;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901605, type, value FROM weenie_properties_float WHERE object_Id = 73260;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901605, type, value FROM weenie_properties_string WHERE object_Id = 73260;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901605, type, value FROM weenie_properties_d_i_d WHERE object_Id = 73260;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901605, type, value FROM weenie_properties_i_i_d WHERE object_Id = 73260;
UPDATE weenie_properties_string SET value = 'Mid Scarecrow Gen' WHERE object_Id = 901605 AND type = 1;
SELECT IF((SELECT value FROM weenie_properties_string WHERE object_Id = 901605 AND type = 34) = 'EventFallFestival', 'gated ok', 'NOT GATED') AS gen_event;
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901605, 0.25, 28881, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_generator WHERE object_Id = 73260 AND weenie_Class_Id = 28877;
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901605, 0.5, 28880, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_generator WHERE object_Id = 73260 AND weenie_Class_Id = 28877;
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901605, 0.75, 28882, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_generator WHERE object_Id = 73260 AND weenie_Class_Id = 28877;
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901605, 1, 8275, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_generator WHERE object_Id = 73260 AND weenie_Class_Id = 28877;

-- 3. nest it in the landscape tables, keeping each table in row order (cumulative probabilities)
--    23151 midnorthforestgen: Pumpkin Lord gen to 0.615366, ours to 0.621366, next row from 0.628191
--    23156 midnorthmountainsgolemsgen: Pumpkin Lord gen to 0.615366, ours to 0.621366, next row from 0.660889
--    23157 midnorthmountainsmattekargen: Pumpkin Lord gen to 0.615366, ours to 0.619301, next row from 0.623237
--    23158 midnorthmountainstuskersgen: Pumpkin Lord gen to 0.615366, ours to 0.621366, next row from 0.629182
--    23159 midnorthplainsgen: Pumpkin Lord gen to 0.615366, ours to 0.621366, next row from 0.629182
--    23191 highnortholthoimountainsgen: Pumpkin Lord gen to 0.615366, ours to 0.621366, next row from 0.746382
--    23193 midnortholthoigen: Pumpkin Lord gen to 0.615366, ours to 0.621366, next row from 0.707098
DROP TEMPORARY TABLE IF EXISTS fs_rows;
DROP TEMPORARY TABLE IF EXISTS fs_pl;
CREATE TEMPORARY TABLE fs_rows AS SELECT id AS k, 0 AS sub, object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_generator WHERE object_Id IN (23151,23156,23157,23158,23159,23191,23193) AND weenie_Class_Id <> 901605;
CREATE TEMPORARY TABLE fs_pl AS SELECT id AS k, object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_generator WHERE object_Id IN (23151,23156,23157,23158,23159,23191,23193) AND weenie_Class_Id = 87048;
INSERT INTO fs_rows (k, sub, object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT k, 1, object_Id, CASE object_Id WHEN 23151 THEN 0.621366 WHEN 23156 THEN 0.621366 WHEN 23157 THEN 0.619301 WHEN 23158 THEN 0.621366 WHEN 23159 THEN 0.621366 WHEN 23191 THEN 0.621366 WHEN 23193 THEN 0.621366 END, 901605, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM fs_pl;
DELETE FROM weenie_properties_generator WHERE object_Id IN (23151,23156,23157,23158,23159,23191,23193);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM fs_rows ORDER BY object_Id, k, sub;
DROP TEMPORARY TABLE fs_rows;
DROP TEMPORARY TABLE fs_pl;
SELECT object_Id, COUNT(*) AS profiles, SUM(weenie_Class_Id = 901605) AS ours FROM weenie_properties_generator WHERE object_Id IN (23151,23156,23157,23158,23159,23191,23193) GROUP BY object_Id;
COMMIT;
