-- HOLTBURG FESTIVAL DRESSING (generated by gen_holtburg_festival.py; docs/SEASONAL-UPGRADE.md "Holtburg festival dressing").
-- Festival Season only: every placed piece is a link child of one Harvest Decorations Gen (900745, EventFallFestival).
START TRANSACTION;

-- ---------------------------------------------------------------- WEENIES 901620-901627 (retail art as world objects)
DELETE FROM weenie_properties_int WHERE object_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
DELETE FROM weenie_properties_int64 WHERE object_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
DELETE FROM weenie_properties_bool WHERE object_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
DELETE FROM weenie_properties_float WHERE object_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
DELETE FROM weenie_properties_string WHERE object_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
DELETE FROM weenie_properties_d_i_d WHERE object_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
DELETE FROM weenie_properties_i_i_d WHERE object_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
DELETE FROM weenie_properties_int WHERE object_Id = 901627;
DELETE FROM weenie_properties_bool WHERE object_Id = 901627;
DELETE FROM weenie_properties_float WHERE object_Id = 901627;
DELETE FROM weenie_properties_string WHERE object_Id = 901627;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901627;
DELETE FROM weenie_properties_attribute WHERE object_Id = 901627;
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901627;
DELETE FROM weenie_properties_skill WHERE object_Id = 901627;
DELETE FROM weenie_properties_body_part WHERE object_Id = 901627;
DELETE FROM weenie_properties_int64 WHERE object_Id = 901627;
DELETE FROM weenie_properties_i_i_d WHERE object_Id = 901627;
DELETE FROM weenie_properties_create_list WHERE object_Id = 901627;
DELETE FROM weenie_properties_palette WHERE object_Id = 901627;
DELETE FROM weenie_properties_texture_map WHERE object_Id = 901627;
DELETE FROM weenie_properties_anim_part WHERE object_Id = 901627;
DELETE FROM weenie_properties_spell_book WHERE object_Id = 901627;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 901627;
DELETE FROM weenie_properties_emote WHERE object_Id = 901627;
DELETE FROM weenie WHERE class_Id IN (901620, 901621, 901622, 901623, 901624, 901625, 901626, 901627);
-- 901620 Jack o' Lantern (art from retail 34138)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901620, 'ace901620-festivaljackolanternevil', 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901620, 1, 128);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901620, 5, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901620, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901620, 19, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901620, 93, 1044);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901620, 3, 76);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901620, 1, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901620, 11, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901620, 13, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901620, 14, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901620, 19, 0);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901620, 39, 1.5);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901620, 12, 0.5);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901620, 1, 'Jack o'' Lantern'), (901620, 16, 'A carved jack o'' lantern, set out by the door for the Festival Season.');
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901620, 1, 33556809);  -- 0x02000949
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901620, 6, 67112968);  -- 0x04001008
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901620, 7, 268437167);  -- 0x100006af
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901620, 8, 100689204);  -- 0x06006534
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901620, 3, 536870932);  -- 0x20000014
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901620, 22, 872415275);  -- 0x3400002b
-- 901621 Jack o' Lantern (art from retail 34139)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901621, 'ace901621-festivaljackolanternpuzzled', 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901621, 1, 128);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901621, 5, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901621, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901621, 19, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901621, 93, 1044);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901621, 3, 76);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901621, 1, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901621, 11, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901621, 13, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901621, 14, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901621, 19, 0);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901621, 39, 1.4);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901621, 12, 0.5);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901621, 1, 'Jack o'' Lantern'), (901621, 16, 'A carved jack o'' lantern, set out by the door for the Festival Season.');
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901621, 1, 33556809);  -- 0x02000949
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901621, 6, 67112968);  -- 0x04001008
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901621, 7, 268437168);  -- 0x100006b0
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901621, 8, 100689205);  -- 0x06006535
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901621, 3, 536870932);  -- 0x20000014
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901621, 22, 872415275);  -- 0x3400002b
-- 901622 Jack o' Lantern (art from retail 34140)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901622, 'ace901622-festivaljackolanternscared', 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901622, 1, 128);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901622, 5, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901622, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901622, 19, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901622, 93, 1044);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901622, 3, 76);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901622, 1, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901622, 11, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901622, 13, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901622, 14, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901622, 19, 0);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901622, 39, 1.35);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901622, 12, 0.5);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901622, 1, 'Jack o'' Lantern'), (901622, 16, 'A carved jack o'' lantern, set out by the door for the Festival Season.');
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901622, 1, 33556809);  -- 0x02000949
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901622, 6, 67112968);  -- 0x04001008
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901622, 7, 268437169);  -- 0x100006b1
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901622, 8, 100689206);  -- 0x06006536
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901622, 3, 536870932);  -- 0x20000014
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901622, 22, 872415275);  -- 0x3400002b
-- 901623 Jack o' Lantern (art from retail 34141)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901623, 'ace901623-festivaljackolanternstupid', 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901623, 1, 128);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901623, 5, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901623, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901623, 19, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901623, 93, 3092);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901623, 3, 76);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901623, 1, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901623, 11, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901623, 13, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901623, 14, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901623, 19, 0);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901623, 39, 1.55);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901623, 12, 0.5);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901623, 1, 'Jack o'' Lantern'), (901623, 16, 'A carved jack o'' lantern, set out by the door for the Festival Season.');
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901623, 1, 33556809);  -- 0x02000949
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901623, 6, 67112968);  -- 0x04001008
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901623, 7, 268437170);  -- 0x100006b2
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901623, 8, 100689207);  -- 0x06006537
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901623, 3, 536870932);  -- 0x20000014
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901623, 22, 872415275);  -- 0x3400002b
-- 901624 Jack o' Lantern (art from retail 8395)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901624, 'ace901624-festivaljackolanternlit', 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901624, 1, 128);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901624, 5, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901624, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901624, 19, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901624, 93, 3092);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901624, 3, 76);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901624, 1, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901624, 11, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901624, 13, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901624, 14, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901624, 19, 0);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901624, 39, 1.45);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901624, 12, 0.0);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901624, 1, 'Jack o'' Lantern'), (901624, 16, 'A carved jack o'' lantern, set out by the door for the Festival Season.');
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901624, 1, 33556858);  -- 0x0200097a
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901624, 6, 67112968);  -- 0x04001008
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901624, 7, 268436044);  -- 0x1000024c
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901624, 8, 100671020);  -- 0x06001e2c
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901624, 3, 536870932);  -- 0x20000014
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901624, 22, 872415275);  -- 0x3400002b
-- 901625 Pumpkin (art from retail 8232)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901625, 'ace901625-festivalpumpkin', 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901625, 1, 128);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901625, 5, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901625, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901625, 19, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901625, 93, 1044);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901625, 1, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901625, 11, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901625, 13, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901625, 14, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901625, 19, 0);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901625, 39, 1.4);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901625, 1, 'Pumpkin'), (901625, 16, 'A bright orange pumpkin, waiting its turn to be carved.');
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901625, 1, 33556809);  -- 0x02000949
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901625, 6, 67112968);  -- 0x04001008
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901625, 7, 268436043);  -- 0x1000024b
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901625, 8, 100671015);  -- 0x06001e27
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901625, 3, 536870932);  -- 0x20000014
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901625, 22, 872415275);  -- 0x3400002b
-- 901626 Great Pumpkin (art from retail 8232)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901626, 'ace901626-festivalgreatpumpkin', 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901626, 1, 128);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901626, 5, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901626, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901626, 19, 0);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901626, 93, 1044);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901626, 1, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901626, 11, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901626, 13, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901626, 14, 1);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901626, 19, 0);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901626, 39, 2.6);
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901626, 1, 'Great Pumpkin'), (901626, 16, 'A huge pumpkin, the pride of some Holtburg garden.');
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901626, 1, 33556809);  -- 0x02000949
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901626, 6, 67112968);  -- 0x04001008
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901626, 7, 268436043);  -- 0x1000024b
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901626, 8, 100671015);  -- 0x06001e27
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901626, 3, 536870932);  -- 0x20000014
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901626, 22, 872415275);  -- 0x3400002b
-- 901627 Scarecrow: an NPC on the animated scarecrow body (clone of Rand 39983 without clothes or emotes)
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901627, 'ace901627-festivalscarecrow', 10);
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901627, type, value FROM weenie_properties_int WHERE object_Id = 39983;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901627, type, value FROM weenie_properties_bool WHERE object_Id = 39983;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901627, type, value FROM weenie_properties_float WHERE object_Id = 39983;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901627, type, value FROM weenie_properties_string WHERE object_Id = 39983;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901627, type, value FROM weenie_properties_d_i_d WHERE object_Id = 39983;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901627, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 39983;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901627, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 39983;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901627, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 39983;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901627, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 39983;
DELETE FROM weenie_properties_int WHERE object_Id = 901627 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901627, 2, 49);
DELETE FROM weenie_properties_int WHERE object_Id = 901627 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901627, 3, 76);
DELETE FROM weenie_properties_int WHERE object_Id = 901627 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901627, 25, 1);
DELETE FROM weenie_properties_float WHERE object_Id = 901627 AND type = 12; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901627, 12, 0.667);
DELETE FROM weenie_properties_float WHERE object_Id = 901627 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901627, 39, 1.0);
DELETE FROM weenie_properties_string WHERE object_Id = 901627 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901627, 1, 'Scarecrow');
DELETE FROM weenie_properties_string WHERE object_Id = 901627 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901627, 16, 'A straw-stuffed scarecrow keeping watch over the Festival Season.');
DELETE FROM weenie_properties_string WHERE object_Id = 901627 AND type = 5;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901627 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901627, 1, 33556868);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901627 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901627, 2, 150995101);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901627 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901627, 3, 536871014);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901627 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901627, 6, 67112967);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901627 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901627, 7, 268436084);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901627 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901627, 8, 100671141);
INSERT INTO weenie_properties_emote (object_Id, category, probability) VALUES (901627, 7, 1);
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) VALUES (@e, 0, 12, 0, 1);
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 1, 10, 0, 1, 'Psst. Over here. Yes, the scarecrow.');
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 2, 10, 1, 1, 'Rand, Game Hunter, is paying for every Vile, Vicious and Villainous Scarecrow put down this Festival Season. Bad straw, the lot of them. Nothing like me.');
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 3, 10, 1, 1, 'They wander the northern wilds while the festival lasts. Rand is at 42.2N, 33.9E, if you are the hunting sort.');

-- ---------------------------------------------------------------- PLACEMENT (landblock 0xA9B4)
DELETE FROM landblock_instance_link WHERE parent_GUID IN (0x7A9B4F02, 0x7A9B4F10, 0x7A9B4F11, 0x7A9B4F05) OR child_GUID IN (0x7A9B4F02, 0x7A9B4F10, 0x7A9B4F11);
DELETE FROM landblock_instance WHERE guid IN (0x7A9B4F02, 0x7A9B4F10, 0x7A9B4F11, 0x7A9B4F05) OR guid BETWEEN 0x7A9B4F20 AND 0x7A9B4F9F;
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES
  (0x7A9B4F05, 900745, 0xA9B40019, 84.0, 20.0, 94.0, 1, 0, 0, 0, 0),  -- Harvest Decorations Gen (EventFallFestival)
  (0x7A9B4F20, 900740, 0xA9B40019, 74.83, 5.3, 94.0, 0.923880, 0, 0, -0.382683, 1),  -- Harvest Lantern Post
  (0x7A9B4F21, 900740, 0xA9B40019, 87.83, 5.3, 94.0, 0.923880, 0, 0, 0.382683, 1),  -- Harvest Lantern Post
  (0x7A9B4F22, 900740, 0xA9B40019, 74.83, 18.3, 94.0, 0.382683, 0, 0, -0.923880, 1),  -- Harvest Lantern Post
  (0x7A9B4F23, 900740, 0xA9B40019, 87.83, 18.3, 94.0, 0.382683, 0, 0, 0.923880, 1),  -- Harvest Lantern Post
  (0x7A9B4F24, 901620, 0xA9B4001A, 74.0, 34.47, 94.0, 0.878817, 0, 0, -0.477159, 1),  -- beside door 0x7A9B401E (R)
  (0x7A9B4F25, 901621, 0xA9B4001A, 76.47, 32.0, 94.0, 0.951057, 0, 0, -0.309017, 1),  -- beside door 0x7A9B401E (L)
  (0x7A9B4F26, 901622, 0xA9B4001A, 80.93, 31.9, 94.0, 0.942641, 0, 0, 0.333807, 1),  -- beside door 0x7A9B401F (R)
  (0x7A9B4F27, 901623, 0xA9B40022, 96.79, 37.75, 94.0, 0.788011, 0, 0, -0.615661, 1),  -- beside door 0x7A9B401A (R)
  (0x7A9B4F28, 901624, 0xA9B40022, 96.79, 34.25, 94.0, 0.688355, 0, 0, -0.725374, 1),  -- beside door 0x7A9B401A (L)
  (0x7A9B4F29, 901620, 0xA9B40022, 119.21, 34.25, 94.0, 0.777146, 0, 0, 0.629320, 1),  -- beside door 0x7A9B401B (R)
  (0x7A9B4F2A, 901621, 0xA9B40022, 119.21, 37.75, 94.0, 0.649448, 0, 0, 0.760406, 1),  -- beside door 0x7A9B401B (L)
  (0x7A9B4F2B, 901622, 0xA9B40029, 134.31, 17.81, 94.0, 0.052336, 0, 0, 0.998630, 1),  -- beside door 0x7A9B4015 (R)
  (0x7A9B4F2C, 901623, 0xA9B4000F, 26.0, 156.48, 66.0, 0.963630, 0, 0, -0.267238, 1),  -- beside door 0x7A9B4005 (R)
  (0x7A9B4F2D, 901624, 0xA9B4000F, 28.47, 154.01, 66.0, 0.913545, 0, 0, -0.406737, 1),  -- beside door 0x7A9B4005 (L)
  (0x7A9B4F2E, 901620, 0xA9B4000F, 32.93, 153.9, 66.0, 0.958820, 0, 0, 0.284015, 1),  -- beside door 0x7A9B4006 (R)
  (0x7A9B4F2F, 901621, 0xA9B4001E, 72.37, 133.29, 66.0, 0.760406, 0, 0, -0.649448, 1),  -- beside door 0x7A9B4003 (R)
  (0x7A9B4F30, 901622, 0xA9B4001E, 72.37, 129.79, 66.0, 0.669131, 0, 0, -0.743145, 1),  -- beside door 0x7A9B4003 (L)
  (0x7A9B4F31, 901623, 0xA9B40016, 59.05, 140.61, 66.0, 0.121869, 0, 0, -0.992546, 1),  -- beside door 0x7A9B400F (R)
  (0x7A9B4F32, 901624, 0xA9B40016, 55.55, 140.61, 66.0, 0.026177, 0, 0, 0.999657, 1),  -- beside door 0x7A9B400F (L)
  (0x7A9B4F33, 901620, 0xA9B40016, 52.1, 136.71, 66.0, 0.629320, 0, 0, -0.777146, 1),  -- beside door 0x7A9B4010 (R)
  (0x7A9B4F34, 901621, 0xA9B40026, 105.91, 141.87, 66.0, 0.078459, 0, 0, -0.996917, 1),  -- beside door 0x7A9B400C (R)
  (0x7A9B4F35, 901622, 0xA9B40026, 102.41, 141.87, 66.0, 0.052336, 0, 0, 0.998630, 1),  -- beside door 0x7A9B400C (L)
  (0x7A9B4F36, 901623, 0xA9B40026, 111.42, 131.68, 66.0, 0.615661, 0, 0, 0.788011, 1),  -- beside door 0x7A9B400D (R)
  (0x7A9B4F37, 901624, 0xA9B40036, 146.8, 132.35, 66.0, 0.913545, 0, 0, -0.406737, 1),  -- beside door 0x7A9B4009 (R)
  (0x7A9B4F38, 901620, 0xA9B40036, 149.27, 129.88, 66.0, 0.878817, 0, 0, -0.477159, 1),  -- beside door 0x7A9B4009 (L)
  (0x7A9B4F39, 901621, 0xA9B40036, 161.46, 133.19, 66.0, 0.309017, 0, 0, 0.951057, 1),  -- beside door 0x7A9B400A (R)
  (0x7A9B4F3A, 901627, 0xA9B40019, 74.5, 22.5, 94.0, 0.959926, 0, 0, 0.280255, 1),  -- square display
  (0x7A9B4F3B, 901626, 0xA9B40019, 75.9, 21.2, 94.0, 0.965896, 0, 0, 0.258931, 1),  -- square display
  (0x7A9B4F3C, 901625, 0xA9B40019, 73.3, 21.3, 94.0, 0.939074, 0, 0, 0.343714, 1),  -- square display
  (0x7A9B4F3D, 901624, 0xA9B40019, 75.6, 23.7, 94.0, 0.974934, 0, 0, 0.222496, 1);  -- square display
INSERT INTO landblock_instance_link (parent_GUID, child_GUID) VALUES
  (0x7A9B4F05, 0x7A9B4F20),
  (0x7A9B4F05, 0x7A9B4F21),
  (0x7A9B4F05, 0x7A9B4F22),
  (0x7A9B4F05, 0x7A9B4F23),
  (0x7A9B4F05, 0x7A9B4F24),
  (0x7A9B4F05, 0x7A9B4F25),
  (0x7A9B4F05, 0x7A9B4F26),
  (0x7A9B4F05, 0x7A9B4F27),
  (0x7A9B4F05, 0x7A9B4F28),
  (0x7A9B4F05, 0x7A9B4F29),
  (0x7A9B4F05, 0x7A9B4F2A),
  (0x7A9B4F05, 0x7A9B4F2B),
  (0x7A9B4F05, 0x7A9B4F2C),
  (0x7A9B4F05, 0x7A9B4F2D),
  (0x7A9B4F05, 0x7A9B4F2E),
  (0x7A9B4F05, 0x7A9B4F2F),
  (0x7A9B4F05, 0x7A9B4F30),
  (0x7A9B4F05, 0x7A9B4F31),
  (0x7A9B4F05, 0x7A9B4F32),
  (0x7A9B4F05, 0x7A9B4F33),
  (0x7A9B4F05, 0x7A9B4F34),
  (0x7A9B4F05, 0x7A9B4F35),
  (0x7A9B4F05, 0x7A9B4F36),
  (0x7A9B4F05, 0x7A9B4F37),
  (0x7A9B4F05, 0x7A9B4F38),
  (0x7A9B4F05, 0x7A9B4F39),
  (0x7A9B4F05, 0x7A9B4F3A),
  (0x7A9B4F05, 0x7A9B4F3B),
  (0x7A9B4F05, 0x7A9B4F3C),
  (0x7A9B4F05, 0x7A9B4F3D);

COMMIT;
-- then (apply-live.sh does it): @clearcache weenie, @clearcache landblock, @reloadblock A9B4 (refused while anyone is in it).
