-- MAINLAND POCKETS: four creature families for four thin pockets of the reachable mainland, level 20-49.
-- Generated by tools/gpubox-ace/mainland_pockets.py; edit that and regenerate.
-- docs/MONSTERS-MAINLAND-POCKETS.md has the gap analysis, the lore, the sites and the playtest list.
--
-- *** MADE, NOT APPLIED. *** To apply (owner's call): back up the landblock_instance rows of the
-- landblocks below, test on ace_world_staging, then
--   ssh gpubox sudo -n mysql ace_world < tools/gpubox-ace/mainland-pockets.sql
--   and in game: @clearcache weenie ; @clearcache landblock ; @reloadblock 95A6 ; @reloadblock 93A6 ; @reloadblock 94A4 ; @reloadblock BDC5 ; @reloadblock BBC4 ; @reloadblock BCC3 ; @reloadblock A06D ; @reloadblock A06C ; @reloadblock A16D ; @reloadblock CD38 ; @reloadblock CB37 ; @reloadblock CB39
-- and copy each expansion/creatures/<name>/<name>.clips.json `intended` block into its wcids/names.
--
-- NEW ROWS ONLY: weenies 901250-901299 and instance guids 0x7LLLLD50-0x7LLLLD5F. Nothing retail is
-- modified. Re-runnable: it deletes its own rows first. Clones read their retail template at run time.
START TRANSACTION;

DELETE FROM landblock_instance WHERE weenie_Class_Id BETWEEN 901250 AND 901299;
DELETE FROM weenie WHERE class_Id BETWEEN 901250 AND 901299;

-- ===== 901250 Tiofor Thornhart, level 28 =====
-- 901250 <- clone of 2582
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901250, 'actioforthornhart', type FROM weenie WHERE class_Id = 2582;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901250, type, value FROM weenie_properties_int WHERE object_Id = 2582;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901250, type, value FROM weenie_properties_int64 WHERE object_Id = 2582;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901250, type, value FROM weenie_properties_bool WHERE object_Id = 2582;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901250, type, value FROM weenie_properties_float WHERE object_Id = 2582;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901250, type, value FROM weenie_properties_string WHERE object_Id = 2582;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901250, type, value FROM weenie_properties_d_i_d WHERE object_Id = 2582;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901250, type, value FROM weenie_properties_i_i_d WHERE object_Id = 2582;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901250, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 2582;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901250, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 2582;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901250, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 2582;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901250, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 2582;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901250, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 2582;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901250, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 2582;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901250, event FROM weenie_properties_event_filter WHERE object_Id = 2582;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901250 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901250 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901250, 1, 'Tiofor Thornhart');
DELETE FROM weenie_properties_int WHERE object_Id = 901250 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901250, 25, 28);
DELETE FROM weenie_properties_int WHERE object_Id = 901250 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901250, 146, 4600);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 39, 2.3);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 31, 20);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901250;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901250, 1, 150, 0, 0), (901250, 2, 140, 0, 0), (901250, 3, 140, 0, 0), (901250, 4, 130, 0, 0), (901250, 5, 60, 0, 0), (901250, 6, 70, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901250;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901250, 1, 60, 0, 0, 130), (901250, 3, 180, 0, 0, 320), (901250, 5, 0, 0, 0, 70);
DELETE FROM weenie_properties_skill WHERE object_Id = 901250;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901250, 6, 0, 2, 0, 85, 0, 0), (901250, 7, 0, 2, 0, 120, 0, 0), (901250, 15, 0, 2, 0, 75, 0, 0), (901250, 45, 0, 2, 0, 125, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 110, armor_Vs_Slash = 110, armor_Vs_Pierce = 110, armor_Vs_Bludgeon = 110, armor_Vs_Cold = 110, armor_Vs_Fire = 110, armor_Vs_Acid = 110, armor_Vs_Electric = 110, armor_Vs_Nether = 110, d_Val = 0, d_Var = 0 WHERE object_Id = 901250;
DELETE FROM weenie_properties_body_part WHERE object_Id = 901250 AND `key` = 22;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 22, d_Var = 0.6 WHERE object_Id = 901250 AND `key` = 0;
UPDATE weenie_properties_body_part SET d_Type = 4, d_Val = 18, d_Var = 0.5 WHERE object_Id = 901250 AND `key` = 10;
UPDATE weenie_properties_body_part SET d_Type = 4, d_Val = 18, d_Var = 0.5 WHERE object_Id = 901250 AND `key` = 13;
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 64, 0.9);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 65, 0.9);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 66, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 67, 1.3);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 68, 0.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 69, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901250 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901250, 70, 1.0);

-- ===== 901251 Thornhart Monarch, level 42 =====
-- 901251 <- clone of 9400
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901251, 'acthornhartmonarch', type FROM weenie WHERE class_Id = 9400;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901251, type, value FROM weenie_properties_int WHERE object_Id = 9400;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901251, type, value FROM weenie_properties_int64 WHERE object_Id = 9400;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901251, type, value FROM weenie_properties_bool WHERE object_Id = 9400;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901251, type, value FROM weenie_properties_float WHERE object_Id = 9400;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901251, type, value FROM weenie_properties_string WHERE object_Id = 9400;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901251, type, value FROM weenie_properties_d_i_d WHERE object_Id = 9400;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901251, type, value FROM weenie_properties_i_i_d WHERE object_Id = 9400;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901251, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 9400;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901251, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 9400;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901251, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 9400;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901251, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 9400;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901251, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 9400;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901251, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 9400;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901251, event FROM weenie_properties_event_filter WHERE object_Id = 9400;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901251 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901251 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901251, 1, 'Thornhart Monarch');
DELETE FROM weenie_properties_int WHERE object_Id = 901251 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901251, 25, 42);
DELETE FROM weenie_properties_int WHERE object_Id = 901251 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901251, 146, 7800);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 39, 2.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 31, 20);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901251;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901251, 1, 200, 0, 0), (901251, 2, 180, 0, 0), (901251, 3, 160, 0, 0), (901251, 4, 150, 0, 0), (901251, 5, 90, 0, 0), (901251, 6, 100, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901251;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901251, 1, 110, 0, 0, 200), (901251, 3, 180, 0, 0, 360), (901251, 5, 0, 0, 0, 100);
DELETE FROM weenie_properties_skill WHERE object_Id = 901251;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901251, 6, 0, 2, 0, 125, 0, 0), (901251, 7, 0, 2, 0, 170, 0, 0), (901251, 15, 0, 2, 0, 110, 0, 0), (901251, 45, 0, 2, 0, 170, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 150, armor_Vs_Slash = 150, armor_Vs_Pierce = 150, armor_Vs_Bludgeon = 150, armor_Vs_Cold = 150, armor_Vs_Fire = 150, armor_Vs_Acid = 150, armor_Vs_Electric = 150, armor_Vs_Nether = 150, d_Val = 0, d_Var = 0 WHERE object_Id = 901251;
DELETE FROM weenie_properties_body_part WHERE object_Id = 901251 AND `key` = 22;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 32, d_Var = 0.6 WHERE object_Id = 901251 AND `key` = 0;
UPDATE weenie_properties_body_part SET d_Type = 4, d_Val = 24, d_Var = 0.5 WHERE object_Id = 901251 AND `key` = 10;
UPDATE weenie_properties_body_part SET d_Type = 4, d_Val = 24, d_Var = 0.5 WHERE object_Id = 901251 AND `key` = 13;
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 64, 0.85);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 65, 0.85);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 66, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 67, 1.25);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 68, 0.75);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 69, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901251 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901251, 70, 1.0);

-- ===== 901252 Shaleback Delver, level 34 =====
-- 901252 <- clone of 7993
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901252, 'acshalebackdelver', type FROM weenie WHERE class_Id = 7993;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901252, type, value FROM weenie_properties_int WHERE object_Id = 7993;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901252, type, value FROM weenie_properties_int64 WHERE object_Id = 7993;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901252, type, value FROM weenie_properties_bool WHERE object_Id = 7993;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901252, type, value FROM weenie_properties_float WHERE object_Id = 7993;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901252, type, value FROM weenie_properties_string WHERE object_Id = 7993;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901252, type, value FROM weenie_properties_d_i_d WHERE object_Id = 7993;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901252, type, value FROM weenie_properties_i_i_d WHERE object_Id = 7993;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901252, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 7993;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901252, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 7993;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901252, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 7993;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901252, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 7993;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901252, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 7993;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901252, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 7993;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901252, event FROM weenie_properties_event_filter WHERE object_Id = 7993;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901252 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901252 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901252, 1, 'Shaleback Delver');
DELETE FROM weenie_properties_int WHERE object_Id = 901252 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901252, 25, 34);
DELETE FROM weenie_properties_int WHERE object_Id = 901252 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901252, 146, 5800);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 39, 0.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 31, 20);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901252;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901252, 1, 200, 0, 0), (901252, 2, 210, 0, 0), (901252, 3, 110, 0, 0), (901252, 4, 110, 0, 0), (901252, 5, 60, 0, 0), (901252, 6, 80, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901252;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901252, 1, 70, 0, 0, 175), (901252, 3, 180, 0, 0, 390), (901252, 5, 0, 0, 0, 80);
DELETE FROM weenie_properties_skill WHERE object_Id = 901252;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901252, 6, 0, 2, 0, 95, 0, 0), (901252, 7, 0, 2, 0, 90, 0, 0), (901252, 15, 0, 2, 0, 95, 0, 0), (901252, 45, 0, 2, 0, 140, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 170, armor_Vs_Slash = 170, armor_Vs_Pierce = 170, armor_Vs_Bludgeon = 170, armor_Vs_Cold = 170, armor_Vs_Fire = 170, armor_Vs_Acid = 170, armor_Vs_Electric = 170, armor_Vs_Nether = 170, d_Val = 0, d_Var = 0 WHERE object_Id = 901252;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 22, d_Var = 0.6 WHERE object_Id = 901252 AND `key` = 0;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 24, d_Var = 0.6 WHERE object_Id = 901252 AND `key` = 10;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 24, d_Var = 0.6 WHERE object_Id = 901252 AND `key` = 13;
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 64, 0.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 65, 0.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 66, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 67, 0.9);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 68, 0.5);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 69, 1.1);
DELETE FROM weenie_properties_float WHERE object_Id = 901252 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901252, 70, 1.1);

-- ===== 901253 Ironvein Shaleback, level 46 =====
-- 901253 <- clone of 7992
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901253, 'acironveinshaleback', type FROM weenie WHERE class_Id = 7992;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901253, type, value FROM weenie_properties_int WHERE object_Id = 7992;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901253, type, value FROM weenie_properties_int64 WHERE object_Id = 7992;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901253, type, value FROM weenie_properties_bool WHERE object_Id = 7992;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901253, type, value FROM weenie_properties_float WHERE object_Id = 7992;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901253, type, value FROM weenie_properties_string WHERE object_Id = 7992;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901253, type, value FROM weenie_properties_d_i_d WHERE object_Id = 7992;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901253, type, value FROM weenie_properties_i_i_d WHERE object_Id = 7992;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901253, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 7992;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901253, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 7992;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901253, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 7992;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901253, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 7992;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901253, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 7992;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901253, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 7992;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901253, event FROM weenie_properties_event_filter WHERE object_Id = 7992;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901253 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901253 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901253, 1, 'Ironvein Shaleback');
DELETE FROM weenie_properties_int WHERE object_Id = 901253 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901253, 25, 46);
DELETE FROM weenie_properties_int WHERE object_Id = 901253 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901253, 146, 8800);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 39, 0.95);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 31, 20);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901253;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901253, 1, 240, 0, 0), (901253, 2, 230, 0, 0), (901253, 3, 120, 0, 0), (901253, 4, 110, 0, 0), (901253, 5, 70, 0, 0), (901253, 6, 90, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901253;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901253, 1, 120, 0, 0, 235), (901253, 3, 180, 0, 0, 410), (901253, 5, 0, 0, 0, 90);
DELETE FROM weenie_properties_skill WHERE object_Id = 901253;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901253, 6, 0, 2, 0, 135, 0, 0), (901253, 7, 0, 2, 0, 120, 0, 0), (901253, 15, 0, 2, 0, 125, 0, 0), (901253, 45, 0, 2, 0, 185, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 210, armor_Vs_Slash = 210, armor_Vs_Pierce = 210, armor_Vs_Bludgeon = 210, armor_Vs_Cold = 210, armor_Vs_Fire = 210, armor_Vs_Acid = 210, armor_Vs_Electric = 210, armor_Vs_Nether = 210, d_Val = 0, d_Var = 0 WHERE object_Id = 901253;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 30, d_Var = 0.6 WHERE object_Id = 901253 AND `key` = 0;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 32, d_Var = 0.6 WHERE object_Id = 901253 AND `key` = 10;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 32, d_Var = 0.6 WHERE object_Id = 901253 AND `key` = 13;
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 64, 0.55);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 65, 0.65);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 66, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 67, 0.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 68, 0.5);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 69, 1.1);
DELETE FROM weenie_properties_float WHERE object_Id = 901253 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901253, 70, 1.2);

-- ===== 901254 Yushad Sandstinger, level 26 =====
-- 901254 <- clone of 208
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901254, 'acyushadsandstinger', type FROM weenie WHERE class_Id = 208;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901254, type, value FROM weenie_properties_int WHERE object_Id = 208;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901254, type, value FROM weenie_properties_int64 WHERE object_Id = 208;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901254, type, value FROM weenie_properties_bool WHERE object_Id = 208;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901254, type, value FROM weenie_properties_float WHERE object_Id = 208;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901254, type, value FROM weenie_properties_string WHERE object_Id = 208;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901254, type, value FROM weenie_properties_d_i_d WHERE object_Id = 208;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901254, type, value FROM weenie_properties_i_i_d WHERE object_Id = 208;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901254, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 208;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901254, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 208;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901254, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 208;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901254, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 208;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901254, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 208;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901254, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 208;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901254, event FROM weenie_properties_event_filter WHERE object_Id = 208;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901254 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901254 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901254, 1, 'Yushad Sandstinger');
DELETE FROM weenie_properties_int WHERE object_Id = 901254 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901254, 25, 26);
DELETE FROM weenie_properties_int WHERE object_Id = 901254 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901254, 146, 4200);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 39, 1.3);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 31, 20);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901254;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901254, 1, 110, 0, 0), (901254, 2, 110, 0, 0), (901254, 3, 130, 0, 0), (901254, 4, 130, 0, 0), (901254, 5, 60, 0, 0), (901254, 6, 60, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901254;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901254, 1, 55, 0, 0, 110), (901254, 3, 180, 0, 0, 290), (901254, 5, 0, 0, 0, 60);
DELETE FROM weenie_properties_skill WHERE object_Id = 901254;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901254, 6, 0, 2, 0, 80, 0, 0), (901254, 7, 0, 2, 0, 110, 0, 0), (901254, 15, 0, 2, 0, 65, 0, 0), (901254, 45, 0, 2, 0, 110, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 120, armor_Vs_Slash = 120, armor_Vs_Pierce = 120, armor_Vs_Bludgeon = 120, armor_Vs_Cold = 120, armor_Vs_Fire = 120, armor_Vs_Acid = 120, armor_Vs_Electric = 120, armor_Vs_Nether = 120, d_Val = 0, d_Var = 0 WHERE object_Id = 901254;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 16, d_Var = 0.6 WHERE object_Id = 901254 AND `key` = 5;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 20, d_Var = 0.7 WHERE object_Id = 901254 AND `key` = 8;
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 64, 0.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 65, 0.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 66, 1.1);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 67, 0.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 68, 1.3);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 69, 0.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901254 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901254, 70, 1.0);

-- ===== 901255 Glassback Stinger, level 38 =====
-- 901255 <- clone of 8215
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901255, 'acglassbackstinger', type FROM weenie WHERE class_Id = 8215;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901255, type, value FROM weenie_properties_int WHERE object_Id = 8215;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901255, type, value FROM weenie_properties_int64 WHERE object_Id = 8215;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901255, type, value FROM weenie_properties_bool WHERE object_Id = 8215;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901255, type, value FROM weenie_properties_float WHERE object_Id = 8215;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901255, type, value FROM weenie_properties_string WHERE object_Id = 8215;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901255, type, value FROM weenie_properties_d_i_d WHERE object_Id = 8215;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901255, type, value FROM weenie_properties_i_i_d WHERE object_Id = 8215;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901255, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 8215;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901255, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 8215;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901255, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 8215;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901255, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 8215;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901255, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 8215;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901255, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 8215;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901255, event FROM weenie_properties_event_filter WHERE object_Id = 8215;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901255 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901255 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901255, 1, 'Glassback Stinger');
DELETE FROM weenie_properties_int WHERE object_Id = 901255 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901255, 25, 38);
DELETE FROM weenie_properties_int WHERE object_Id = 901255 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901255, 146, 6600);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 39, 1.55);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 31, 20);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901255;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901255, 1, 160, 0, 0), (901255, 2, 160, 0, 0), (901255, 3, 150, 0, 0), (901255, 4, 150, 0, 0), (901255, 5, 80, 0, 0), (901255, 6, 80, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901255;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901255, 1, 90, 0, 0, 170), (901255, 3, 180, 0, 0, 340), (901255, 5, 0, 0, 0, 80);
DELETE FROM weenie_properties_skill WHERE object_Id = 901255;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901255, 6, 0, 2, 0, 115, 0, 0), (901255, 7, 0, 2, 0, 150, 0, 0), (901255, 15, 0, 2, 0, 100, 0, 0), (901255, 45, 0, 2, 0, 155, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 170, armor_Vs_Slash = 170, armor_Vs_Pierce = 170, armor_Vs_Bludgeon = 170, armor_Vs_Cold = 170, armor_Vs_Fire = 170, armor_Vs_Acid = 170, armor_Vs_Electric = 170, armor_Vs_Nether = 170, d_Val = 0, d_Var = 0 WHERE object_Id = 901255;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 22, d_Var = 0.6 WHERE object_Id = 901255 AND `key` = 5;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 28, d_Var = 0.7 WHERE object_Id = 901255 AND `key` = 8;
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 64, 0.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 65, 0.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 66, 1.3);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 67, 0.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 68, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 69, 0.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901255 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901255, 70, 0.8);

-- ===== 901256 Crag Shrike, level 36 =====
-- 901256 <- clone of 1615
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901256, 'accragshrike', type FROM weenie WHERE class_Id = 1615;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901256, type, value FROM weenie_properties_int WHERE object_Id = 1615;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901256, type, value FROM weenie_properties_int64 WHERE object_Id = 1615;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901256, type, value FROM weenie_properties_bool WHERE object_Id = 1615;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901256, type, value FROM weenie_properties_float WHERE object_Id = 1615;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901256, type, value FROM weenie_properties_string WHERE object_Id = 1615;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901256, type, value FROM weenie_properties_d_i_d WHERE object_Id = 1615;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901256, type, value FROM weenie_properties_i_i_d WHERE object_Id = 1615;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901256, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 1615;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901256, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 1615;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901256, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 1615;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901256, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 1615;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901256, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 1615;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901256, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 1615;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901256, event FROM weenie_properties_event_filter WHERE object_Id = 1615;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901256 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901256 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901256, 1, 'Crag Shrike');
DELETE FROM weenie_properties_int WHERE object_Id = 901256 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901256, 25, 36);
DELETE FROM weenie_properties_int WHERE object_Id = 901256 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901256, 146, 6200);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 39, 1.3);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 31, 20);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901256 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901256, 3, 536871034);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901256;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901256, 1, 150, 0, 0), (901256, 2, 140, 0, 0), (901256, 3, 180, 0, 0), (901256, 4, 170, 0, 0), (901256, 5, 70, 0, 0), (901256, 6, 60, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901256;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901256, 1, 70, 0, 0, 140), (901256, 3, 180, 0, 0, 320), (901256, 5, 0, 0, 0, 60);
DELETE FROM weenie_properties_skill WHERE object_Id = 901256;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901256, 6, 0, 2, 0, 110, 0, 0), (901256, 7, 0, 2, 0, 140, 0, 0), (901256, 15, 0, 2, 0, 85, 0, 0), (901256, 45, 0, 2, 0, 150, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 120, armor_Vs_Slash = 120, armor_Vs_Pierce = 120, armor_Vs_Bludgeon = 120, armor_Vs_Cold = 120, armor_Vs_Fire = 120, armor_Vs_Acid = 120, armor_Vs_Electric = 120, armor_Vs_Nether = 120, d_Val = 0, d_Var = 0 WHERE object_Id = 901256;
DELETE FROM weenie_properties_body_part WHERE object_Id = 901256 AND `key` = 22;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 26, d_Var = 0.6 WHERE object_Id = 901256 AND `key` = 0;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 14, d_Var = 0.5 WHERE object_Id = 901256 AND `key` = 5;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 24, d_Var = 0.6 WHERE object_Id = 901256 AND `key` = 8;
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 64, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 65, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 66, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 67, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 68, 0.7);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 69, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901256 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901256, 70, 1.0);

-- ===== 901257 Snowcrest Shrike, level 47 =====
-- 901257 <- clone of 1615
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901257, 'acsnowcrestshrike', type FROM weenie WHERE class_Id = 1615;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901257, type, value FROM weenie_properties_int WHERE object_Id = 1615;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901257, type, value FROM weenie_properties_int64 WHERE object_Id = 1615;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901257, type, value FROM weenie_properties_bool WHERE object_Id = 1615;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901257, type, value FROM weenie_properties_float WHERE object_Id = 1615;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901257, type, value FROM weenie_properties_string WHERE object_Id = 1615;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901257, type, value FROM weenie_properties_d_i_d WHERE object_Id = 1615;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901257, type, value FROM weenie_properties_i_i_d WHERE object_Id = 1615;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901257, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 1615;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901257, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 1615;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901257, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 1615;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901257, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 1615;
INSERT INTO weenie_properties_body_part (object_Id, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b) SELECT 901257, `key`, d_Type, d_Val, d_Var, base_Armor, armor_Vs_Slash, armor_Vs_Pierce, armor_Vs_Bludgeon, armor_Vs_Cold, armor_Vs_Fire, armor_Vs_Acid, armor_Vs_Electric, armor_Vs_Nether, b_h, h_l_f, m_l_f, l_l_f, h_r_f, m_r_f, l_r_f, h_l_b, m_l_b, l_l_b, h_r_b, m_r_b, l_r_b FROM weenie_properties_body_part WHERE object_Id = 1615;
INSERT INTO weenie_properties_position (object_Id, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) SELECT 901257, position_Type, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z FROM weenie_properties_position WHERE object_Id = 1615;
INSERT INTO weenie_properties_event_filter (object_Id, event) SELECT 901257, event FROM weenie_properties_event_filter WHERE object_Id = 1615;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901257 AND type = 7;   -- ClothingBase: never read (ownAppearance)
DELETE FROM weenie_properties_string WHERE object_Id = 901257 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901257, 1, 'Snowcrest Shrike');
DELETE FROM weenie_properties_int WHERE object_Id = 901257 AND type = 25; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901257, 25, 47);
DELETE FROM weenie_properties_int WHERE object_Id = 901257 AND type = 146; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901257, 146, 9200);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 39, 1.5);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 31; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 31, 20);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901257 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901257, 3, 536871034);
DELETE FROM weenie_properties_attribute WHERE object_Id = 901257;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) VALUES (901257, 1, 190, 0, 0), (901257, 2, 180, 0, 0), (901257, 3, 220, 0, 0), (901257, 4, 200, 0, 0), (901257, 5, 80, 0, 0), (901257, 6, 70, 0, 0);
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id = 901257;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) VALUES (901257, 1, 120, 0, 0, 210), (901257, 3, 180, 0, 0, 360), (901257, 5, 0, 0, 0, 70);
DELETE FROM weenie_properties_skill WHERE object_Id = 901257;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) VALUES (901257, 6, 0, 2, 0, 145, 0, 0), (901257, 7, 0, 2, 0, 180, 0, 0), (901257, 15, 0, 2, 0, 115, 0, 0), (901257, 45, 0, 2, 0, 190, 0, 0);
UPDATE weenie_properties_body_part SET base_Armor = 160, armor_Vs_Slash = 160, armor_Vs_Pierce = 160, armor_Vs_Bludgeon = 160, armor_Vs_Cold = 160, armor_Vs_Fire = 160, armor_Vs_Acid = 160, armor_Vs_Electric = 160, armor_Vs_Nether = 160, d_Val = 0, d_Var = 0 WHERE object_Id = 901257;
DELETE FROM weenie_properties_body_part WHERE object_Id = 901257 AND `key` = 22;
UPDATE weenie_properties_body_part SET d_Type = 2, d_Val = 34, d_Var = 0.6 WHERE object_Id = 901257 AND `key` = 0;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 18, d_Var = 0.5 WHERE object_Id = 901257 AND `key` = 5;
UPDATE weenie_properties_body_part SET d_Type = 1, d_Val = 32, d_Var = 0.6 WHERE object_Id = 901257 AND `key` = 8;
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 64; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 64, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 65; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 65, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 66; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 66, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 67; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 67, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 68; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 68, 0.4);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 69; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 69, 1.0);
DELETE FROM weenie_properties_float WHERE object_Id = 901257 AND type = 70; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901257, 70, 1.0);

-- ===== 901270 Thornhart Gen: 3 of 901250 every 5 min and one 901251 every 15 min, scattered 15 m =====
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901270, 'acthornhartgen', 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901270 AND type = 81; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901270, 81, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 901270 AND type = 82; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901270, 82, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 901270 AND type = 93; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901270, 93, 1044);
DELETE FROM weenie_properties_bool WHERE object_Id = 901270 AND type = 1; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901270, 1, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901270 AND type = 11; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901270, 11, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901270 AND type = 18; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901270, 18, 1);
DELETE FROM weenie_properties_float WHERE object_Id = 901270 AND type = 41; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901270, 41, 60);
DELETE FROM weenie_properties_float WHERE object_Id = 901270 AND type = 43; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901270, 43, 15.0);
DELETE FROM weenie_properties_string WHERE object_Id = 901270 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901270, 1, 'Thornhart Gen');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901270 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901270, 1, 33555051);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901270 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901270, 8, 100667494);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901270, -1, 901250, 300, 3, 3, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901270, -1, 901251, 900, 1, 1, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);

-- ===== 901271 Shaleback Gen: 2 of 901252 every 5 min and one 901253 every 15 min, scattered 12 m =====
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901271, 'acshalebackgen', 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901271 AND type = 81; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901271, 81, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 901271 AND type = 82; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901271, 82, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 901271 AND type = 93; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901271, 93, 1044);
DELETE FROM weenie_properties_bool WHERE object_Id = 901271 AND type = 1; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901271, 1, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901271 AND type = 11; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901271, 11, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901271 AND type = 18; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901271, 18, 1);
DELETE FROM weenie_properties_float WHERE object_Id = 901271 AND type = 41; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901271, 41, 60);
DELETE FROM weenie_properties_float WHERE object_Id = 901271 AND type = 43; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901271, 43, 12.0);
DELETE FROM weenie_properties_string WHERE object_Id = 901271 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901271, 1, 'Shaleback Gen');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901271 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901271, 1, 33555051);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901271 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901271, 8, 100667494);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901271, -1, 901252, 300, 2, 2, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901271, -1, 901253, 900, 1, 1, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);

-- ===== 901272 Sandstinger Gen: 3 of 901254 every 5 min and one 901255 every 15 min, scattered 12 m =====
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901272, 'acsandstingergen', 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901272 AND type = 81; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901272, 81, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 901272 AND type = 82; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901272, 82, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 901272 AND type = 93; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901272, 93, 1044);
DELETE FROM weenie_properties_bool WHERE object_Id = 901272 AND type = 1; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901272, 1, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901272 AND type = 11; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901272, 11, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901272 AND type = 18; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901272, 18, 1);
DELETE FROM weenie_properties_float WHERE object_Id = 901272 AND type = 41; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901272, 41, 60);
DELETE FROM weenie_properties_float WHERE object_Id = 901272 AND type = 43; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901272, 43, 12.0);
DELETE FROM weenie_properties_string WHERE object_Id = 901272 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901272, 1, 'Sandstinger Gen');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901272 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901272, 1, 33555051);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901272 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901272, 8, 100667494);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901272, -1, 901254, 300, 3, 3, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901272, -1, 901255, 900, 1, 1, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);

-- ===== 901273 Crag Shrike Gen: 2 of 901256 every 5 min and one 901257 every 20 min, scattered 15 m =====
INSERT INTO weenie (class_Id, class_Name, type) VALUES (901273, 'accragshrikegen', 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901273 AND type = 81; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901273, 81, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 901273 AND type = 82; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901273, 82, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 901273 AND type = 93; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901273, 93, 1044);
DELETE FROM weenie_properties_bool WHERE object_Id = 901273 AND type = 1; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901273, 1, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901273 AND type = 11; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901273, 11, 1);
DELETE FROM weenie_properties_bool WHERE object_Id = 901273 AND type = 18; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901273, 18, 1);
DELETE FROM weenie_properties_float WHERE object_Id = 901273 AND type = 41; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901273, 41, 60);
DELETE FROM weenie_properties_float WHERE object_Id = 901273 AND type = 43; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901273, 43, 15.0);
DELETE FROM weenie_properties_string WHERE object_Id = 901273 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901273, 1, 'Crag Shrike Gen');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901273 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901273, 1, 33555051);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901273 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901273, 8, 100667494);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901273, -1, 901256, 300, 2, 2, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);
INSERT INTO weenie_properties_generator (object_Id, probability, weenie_Class_Id, delay, init_Create, max_Create, when_Create, where_Create, stack_Size, palette_Id, shade, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z) VALUES (901273, -1, 901257, 1200, 1, 1, 1, 2, -1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0);

-- ===== placements =====
-- Thornhart Gen: 31.5N 17.6E, Tiofor Woods by the Banderling Tower
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x795A6D50, 901270, 0x95A6001F, 84.0, 156.0, 64.0, 1, 0, 0, 0, 0);
-- Thornhart Gen: 31.3N 15.7E, Tiofor Woods west
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x793A6D51, 901270, 0x93A60005, 12.0, 108.0, 40.0, 1, 0, 0, 0, 0);
-- Thornhart Gen: 29.3N 17.1E, Tiofor Woods above Howling Wolf Villas
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x794A4D52, 901270, 0x94A40031, 156.0, 12.0, 56.5, 1, 0, 0, 0, 0);
-- Shaleback Gen: 55.8N 49.8E, the ice between Colier and Bandit Castle
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7BDC5D54, 901271, 0xBDC5002A, 132.0, 36.0, 278.5, 1, 0, 0, 0, 0);
-- Shaleback Gen: 55.5N 48.1E, below the North Mountain portals
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7BBC4D55, 901271, 0xBBC40027, 108.0, 156.0, 272.0, 1, 0, 0, 0, 0);
-- Shaleback Gen: 54.2N 49.0E, the ice field's south end
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7BCC3D56, 901271, 0xBCC3002A, 132.0, 36.0, 280.0, 1, 0, 0, 0, 0);
-- Sandstinger Gen: 14.3S 26.1E, the rock-strewn sand below the Yushad Ridge
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7A06DD58, 901272, 0xA06D0005, 12.0, 108.0, 24.0, 1, 0, 0, 0, 0);
-- Sandstinger Gen: 15.5S 26.5E, the Samsur-Uziz road's east
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7A06CD59, 901272, 0xA06C0021, 108.0, 12.0, 24.0, 1, 0, 0, 0, 0);
-- Sandstinger Gen: 14.4S 27.2E, north of Dragon's Lair
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7A16DD5A, 901272, 0xA16D001C, 84.0, 84.0, 24.0, 1, 0, 0, 0, 0);
-- Crag Shrike Gen: 56.9S 62.2E, the white-rock heights south of Baishi
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7CD38D5C, 901273, 0xCD38000B, 36.0, 60.0, 183.0, 1, 0, 0, 0, 0);
-- Crag Shrike Gen: 57.6S 60.5E, below the Ridge Tower
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7CB37D5D, 901273, 0xCB370004, 12.0, 84.0, 183.0, 1, 0, 0, 0, 0);
-- Crag Shrike Gen: 56.1S 60.7E, the scree west of the Baishi road
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7CB39D5E, 901273, 0xCB390013, 60.0, 60.0, 217.5, 1, 0, 0, 0, 0);

COMMIT;
