-- RIFTWATCHER YSANNE, weenie 901420: teaches Nether Rift (spell 60001) at the Encampment near Rynthid
-- Infested Plains, 61.6S 63.3W (docs/NEW-ANIMATIONS.md section 7). Generated by nether_rift_trainer.py.
-- Looks from retail's Professor of Void Magic (53385), no emote data: RevivalGuard NetherRift.cs speaks for her.
-- Re-runnable: deletes weenies 901420-901429 and their instances first. Apply with apply-live.sh ... 3032.
START TRANSACTION;
DELETE FROM landblock_instance WHERE weenie_Class_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_int WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_int64 WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_bool WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_float WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_string WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_d_i_d WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_i_i_d WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_attribute WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_skill WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_spell_book WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_body_part WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_create_list WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_palette WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_texture_map WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_anim_part WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_position WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_event_filter WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_emote WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_generator WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_book WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie_properties_book_page_data WHERE object_Id BETWEEN 901420 AND 901429;
DELETE FROM weenie WHERE class_Id BETWEEN 901420 AND 901429;

-- 901420 <- clone of 53385 (Professor of Void Magic), emotes left behind
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901420, 'acriftwatcherysanne', type FROM weenie WHERE class_Id = 53385;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901420, type, value FROM weenie_properties_int WHERE object_Id = 53385;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901420, type, value FROM weenie_properties_int64 WHERE object_Id = 53385;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901420, type, value FROM weenie_properties_bool WHERE object_Id = 53385;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901420, type, value FROM weenie_properties_float WHERE object_Id = 53385;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901420, type, value FROM weenie_properties_string WHERE object_Id = 53385;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901420, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53385;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901420, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53385;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 901420, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 53385;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 901420, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 53385;
INSERT INTO weenie_properties_skill (object_Id, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time) SELECT 901420, type, level_From_P_P, s_a_c, p_p, init_Level, resistance_At_Last_Check, last_Used_Time FROM weenie_properties_skill WHERE object_Id = 53385;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901420, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 53385;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901420, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 53385;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 901420, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 53385;
UPDATE weenie_properties_string SET value = 'Riftwatcher Ysanne' WHERE object_Id = 901420 AND type = 1;
UPDATE weenie_properties_string SET value = 'Void Instructor' WHERE object_Id = 901420 AND type = 5;

-- placed at 57.5, 88.5, 132.03 in cell 0x30320014
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child, last_Modified) VALUES (1929587010, 901420, 808583188, 57.5, 88.5, 132.03, 0.535819, 0, 0, -0.844333, 0, NOW());
COMMIT;
