-- THE SERPENT ARMS, weenies 901900-901909 (owner, 2026-10-01: "make more weapons that look like the serpents flight").
-- Generated by tools/gpubox-ace/serpent_arms.py -- edit that, not this. Design: docs/SERPENT-WEAPONS.md.
-- Art: expansion/weapons/serpent/ (models expansion/models/0x01FF1900-0x01FF1909.glb, w901900-w901909.glb).
--
-- Each weapon clones a retail rare of its family and skill (Serpent's Flight's tier) and changes only:
-- name, description, setup, icon, PaletteBase, DefaultScale, RareId, damage type + its rending imbue,
-- the spell book, and one anim_part row (index 0 -> our GfxObj). Also lists all ten on the Keeper of
-- Lost Things (901000, Hotel Swank). No player source yet.
--   ssh gpubox '~/Dereth-Unity/tools/gpubox-ace/apply-live.sh tools/gpubox-ace/serpent-arms.sql 018A'
START TRANSACTION;

DELETE FROM weenie_properties_int WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_int64 WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_bool WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_float WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_d_i_d WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_i_i_d WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_string WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_spell_book WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie_properties_anim_part WHERE object_Id BETWEEN 901900 AND 901949;
DELETE FROM weenie WHERE class_Id BETWEEN 901900 AND 901949;

-- ---------------------------------------------------------------- 901900 Serpent's Verdict (clone of retail rare 30333 Morrigan's Vanity; base setup 0x02000065 Long Sword)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901900, 'ace901900-serpentsverdict', type, NOW() FROM weenie WHERE class_Id = 30333;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901900, type, value FROM weenie_properties_int WHERE object_Id = 30333;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901900, type, value FROM weenie_properties_int64 WHERE object_Id = 30333;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901900, type, value FROM weenie_properties_bool WHERE object_Id = 30333;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901900, type, value FROM weenie_properties_float WHERE object_Id = 30333;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901900, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30333;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901900, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30333;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901900, type, value FROM weenie_properties_string WHERE object_Id = 30333;
DELETE FROM weenie_properties_string WHERE object_Id = 901900 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901900, 1, 'Serpent''s Verdict');
DELETE FROM weenie_properties_string WHERE object_Id = 901900 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901900, 16, 'Before he took up the bow, Judge Fang wore this blade to the bench and drew it only to pronounce sentence. His students say the serpent at its pommel watched every man brought before him, and never once blinked at a lie.');
DELETE FROM weenie_properties_string WHERE object_Id = 901900 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901900 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901900, 1, 33554533);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901900 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901900, 8, 117381376);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901900 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901900, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901900 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901900 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901900 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901900 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901900 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901900, 45, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 901900 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901900, 179, 8);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901900, 3965, 2), (901900, 4400, 2), (901900, 4624, 2), (901900, 4596, 2), (901900, 4661, 2), (901900, 4682, 2), (901900, 4712, 2), (901900, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901900, 0, 33495296);   -- 0x01FF1900

-- ---------------------------------------------------------------- 901901 Serpent's Hood (clone of retail rare 30343 Smite; base setup 0x02000125 Battle Axe)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901901, 'ace901901-serpentshood', type, NOW() FROM weenie WHERE class_Id = 30343;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901901, type, value FROM weenie_properties_int WHERE object_Id = 30343;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901901, type, value FROM weenie_properties_int64 WHERE object_Id = 30343;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901901, type, value FROM weenie_properties_bool WHERE object_Id = 30343;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901901, type, value FROM weenie_properties_float WHERE object_Id = 30343;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901901, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30343;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901901, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30343;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901901, type, value FROM weenie_properties_string WHERE object_Id = 30343;
DELETE FROM weenie_properties_string WHERE object_Id = 901901 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901901, 1, 'Serpent''s Hood');
DELETE FROM weenie_properties_string WHERE object_Id = 901901 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901901, 16, 'A cobra spreads its hood before it strikes, and so gives fair warning. Judge Fang''s students forged this axe to the same rule: the hood is the edge, and the red eye on its cheek is the warning.');
DELETE FROM weenie_properties_string WHERE object_Id = 901901 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901901 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901901, 1, 33554725);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901901 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901901, 8, 117381377);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901901 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901901, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901901 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901901 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901901 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901901 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901901 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901901, 45, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901901 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901901, 179, 8);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901901, 3965, 2), (901901, 4400, 2), (901901, 4624, 2), (901901, 4596, 2), (901901, 4661, 2), (901901, 4682, 2), (901901, 4712, 2), (901901, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901901, 0, 33495297);   -- 0x01FF1901

-- ---------------------------------------------------------------- 901902 Serpent's Coil (clone of retail rare 30312 Baton of Tirethas; base setup 0x0200013A Mace)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901902, 'ace901902-serpentscoil', type, NOW() FROM weenie WHERE class_Id = 30312;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901902, type, value FROM weenie_properties_int WHERE object_Id = 30312;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901902, type, value FROM weenie_properties_int64 WHERE object_Id = 30312;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901902, type, value FROM weenie_properties_bool WHERE object_Id = 30312;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901902, type, value FROM weenie_properties_float WHERE object_Id = 30312;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901902, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30312;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901902, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30312;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901902, type, value FROM weenie_properties_string WHERE object_Id = 30312;
DELETE FROM weenie_properties_string WHERE object_Id = 901902 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901902, 1, 'Serpent''s Coil');
DELETE FROM weenie_properties_string WHERE object_Id = 901902 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901902, 16, 'A serpent coiled is a serpent at rest, and a serpent at rest is still a serpent. So the Sho scholars taught, and so this mace was wound, its tongue flicking from the coils.');
DELETE FROM weenie_properties_string WHERE object_Id = 901902 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901902 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901902, 1, 33554746);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901902 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901902, 8, 117381378);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901902 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901902, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901902 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901902 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901902 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901902 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901902 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901902, 45, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 901902 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901902, 179, 32);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901902, 3965, 2), (901902, 4400, 2), (901902, 4518, 2), (901902, 4596, 2), (901902, 4661, 2), (901902, 4682, 2), (901902, 4686, 2), (901902, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901902, 0, 33495298);   -- 0x01FF1902

-- ---------------------------------------------------------------- 901903 Serpent's Strike (clone of retail rare 30321 Squire's Glaive; base setup 0x02000144 Spear)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901903, 'ace901903-serpentsstrike', type, NOW() FROM weenie WHERE class_Id = 30321;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901903, type, value FROM weenie_properties_int WHERE object_Id = 30321;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901903, type, value FROM weenie_properties_int64 WHERE object_Id = 30321;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901903, type, value FROM weenie_properties_bool WHERE object_Id = 30321;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901903, type, value FROM weenie_properties_float WHERE object_Id = 30321;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901903, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30321;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901903, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30321;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901903, type, value FROM weenie_properties_string WHERE object_Id = 30321;
DELETE FROM weenie_properties_string WHERE object_Id = 901903 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901903, 1, 'Serpent''s Strike');
DELETE FROM weenie_properties_string WHERE object_Id = 901903 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901903, 16, 'Judge Fang held that justice should reach as far as a serpent strikes, and no farther. The scholars who kept his workshop after his death made this spear to that measure.');
DELETE FROM weenie_properties_string WHERE object_Id = 901903 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901903 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901903, 1, 33554756);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901903 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901903, 8, 117381379);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901903 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901903, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901903 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901903 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901903 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901903 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901903 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901903, 45, 2);
DELETE FROM weenie_properties_int WHERE object_Id = 901903 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901903, 179, 16);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901903, 3965, 2), (901903, 4400, 2), (901903, 4518, 2), (901903, 4596, 2), (901903, 4661, 2), (901903, 4682, 2), (901903, 4686, 2), (901903, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901903, 0, 33495299);   -- 0x01FF1903

-- ---------------------------------------------------------------- 901904 Serpent's Wisdom (clone of retail rare 30326 Staff of Fettered Souls; base setup 0x0200013D Quarter Staff)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901904, 'ace901904-serpentswisdom', type, NOW() FROM weenie WHERE class_Id = 30326;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901904, type, value FROM weenie_properties_int WHERE object_Id = 30326;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901904, type, value FROM weenie_properties_int64 WHERE object_Id = 30326;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901904, type, value FROM weenie_properties_bool WHERE object_Id = 30326;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901904, type, value FROM weenie_properties_float WHERE object_Id = 30326;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901904, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30326;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901904, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30326;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901904, type, value FROM weenie_properties_string WHERE object_Id = 30326;
DELETE FROM weenie_properties_string WHERE object_Id = 901904 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901904, 1, 'Serpent''s Wisdom');
DELETE FROM weenie_properties_string WHERE object_Id = 901904 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901904, 16, 'Two serpents climb this staff and look both ways at once, as a magistrate must. The Sho carry it as a mark of learning, and the wise among them carry it as a weapon too.');
DELETE FROM weenie_properties_string WHERE object_Id = 901904 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901904 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901904, 1, 33554749);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901904 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901904, 8, 117381380);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901904 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901904, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901904 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901904 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901904 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901904 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901904 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901904, 45, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 901904 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901904, 179, 32);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901904, 3965, 2), (901904, 4400, 2), (901904, 4518, 2), (901904, 4596, 2), (901904, 4661, 2), (901904, 4682, 2), (901904, 4686, 2), (901904, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901904, 0, 33495300);   -- 0x01FF1904

-- ---------------------------------------------------------------- 901905 Serpent's Tooth (clone of retail rare 30311 Zharalim Crookblade; base setup 0x0200012F Dagger)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901905, 'ace901905-serpentstooth', type, NOW() FROM weenie WHERE class_Id = 30311;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901905, type, value FROM weenie_properties_int WHERE object_Id = 30311;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901905, type, value FROM weenie_properties_int64 WHERE object_Id = 30311;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901905, type, value FROM weenie_properties_bool WHERE object_Id = 30311;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901905, type, value FROM weenie_properties_float WHERE object_Id = 30311;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901905, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30311;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901905, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30311;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901905, type, value FROM weenie_properties_string WHERE object_Id = 30311;
DELETE FROM weenie_properties_string WHERE object_Id = 901905 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901905, 1, 'Serpent''s Tooth');
DELETE FROM weenie_properties_string WHERE object_Id = 901905 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901905, 16, 'A single fang, shed and grown again. Sho scholars give such blades to students who have mastered their texts, for the serpent renews itself, and so must learning.');
DELETE FROM weenie_properties_string WHERE object_Id = 901905 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901905 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901905, 1, 33554735);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901905 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901905, 8, 117381381);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901905 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901905, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901905 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901905 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901905 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901905 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901905 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901905, 45, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 901905 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901905, 179, 8);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901905, 3963, 2), (901905, 4400, 2), (901905, 4538, 2), (901905, 4596, 2), (901905, 4661, 2), (901905, 4682, 2), (901905, 4691, 2), (901905, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901905, 0, 33495301);   -- 0x01FF1905

-- ---------------------------------------------------------------- 901906 Serpent's Kiss (clone of retail rare 30336 Malachite Slasher; base setup 0x02000137 Katar)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901906, 'ace901906-serpentskiss', type, NOW() FROM weenie WHERE class_Id = 30336;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901906, type, value FROM weenie_properties_int WHERE object_Id = 30336;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901906, type, value FROM weenie_properties_int64 WHERE object_Id = 30336;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901906, type, value FROM weenie_properties_bool WHERE object_Id = 30336;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901906, type, value FROM weenie_properties_float WHERE object_Id = 30336;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901906, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30336;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901906, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30336;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901906, type, value FROM weenie_properties_string WHERE object_Id = 30336;
DELETE FROM weenie_properties_string WHERE object_Id = 901906 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901906, 1, 'Serpent''s Kiss');
DELETE FROM weenie_properties_string WHERE object_Id = 901906 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901906, 16, 'The serpent''s kiss is quick and leaves three marks. Judge Fang''s students worked the fins of his bow into this katar, so that the hand which wears it strikes as the serpent does.');
DELETE FROM weenie_properties_string WHERE object_Id = 901906 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901906 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901906, 1, 33554743);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901906 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901906, 8, 117381382);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901906 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901906, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901906 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901906 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901906 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901906 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901906 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901906, 45, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901906 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901906, 179, 8);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901906, 3963, 2), (901906, 4400, 2), (901906, 4538, 2), (901906, 4596, 2), (901906, 4661, 2), (901906, 4682, 2), (901906, 4691, 2), (901906, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901906, 0, 33495302);   -- 0x01FF1906

-- ---------------------------------------------------------------- 901907 Serpent's Spite (clone of retail rare 30305 Bloodmark Crossbow; base setup 0x0200134C Zefir's Breath (crossbow))
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901907, 'ace901907-serpentsspite', type, NOW() FROM weenie WHERE class_Id = 30305;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901907, type, value FROM weenie_properties_int WHERE object_Id = 30305;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901907, type, value FROM weenie_properties_int64 WHERE object_Id = 30305;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901907, type, value FROM weenie_properties_bool WHERE object_Id = 30305;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901907, type, value FROM weenie_properties_float WHERE object_Id = 30305;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901907, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30305;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901907, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30305;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901907, type, value FROM weenie_properties_string WHERE object_Id = 30305;
DELETE FROM weenie_properties_string WHERE object_Id = 901907 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901907, 1, 'Serpent''s Spite');
DELETE FROM weenie_properties_string WHERE object_Id = 901907 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901907, 16, 'Judge Fang''s students could not agree which of them should inherit Serpent''s Flight, so each built a lesser bow of their own. This crossbow is the spiteful one.');
DELETE FROM weenie_properties_string WHERE object_Id = 901907 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901907 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901907, 1, 33559372);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901907 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901907, 8, 117381383);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901907 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901907, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901907 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901907 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901907 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901907 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901907 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901907, 45, 2);
DELETE FROM weenie_properties_int WHERE object_Id = 901907 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901907, 179, 16);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901907, 3963, 2), (901907, 4400, 2), (901907, 4522, 2), (901907, 4596, 2), (901907, 4661, 2), (901907, 4682, 2), (901907, 4713, 2), (901907, 5183, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901907, 0, 33495303);   -- 0x01FF1907

-- ---------------------------------------------------------------- 901908 Serpent's Eye (clone of retail rare 30377 Wings of Rakhil; base setup 0x0200017C Wand)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901908, 'ace901908-serpentseye', type, NOW() FROM weenie WHERE class_Id = 30377;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901908, type, value FROM weenie_properties_int WHERE object_Id = 30377;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901908, type, value FROM weenie_properties_int64 WHERE object_Id = 30377;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901908, type, value FROM weenie_properties_bool WHERE object_Id = 30377;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901908, type, value FROM weenie_properties_float WHERE object_Id = 30377;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901908, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30377;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901908, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30377;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901908, type, value FROM weenie_properties_string WHERE object_Id = 30377;
DELETE FROM weenie_properties_string WHERE object_Id = 901908 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901908, 1, 'Serpent''s Eye');
DELETE FROM weenie_properties_string WHERE object_Id = 901908 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901908, 16, 'The red eye of the serpent sees what the scholar has not yet read. Sho magistrates were said to carry such wands to the bench, and to read in them whether a witness lied.');
DELETE FROM weenie_properties_string WHERE object_Id = 901908 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901908 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901908, 1, 33554812);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901908 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901908, 8, 117381384);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901908 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901908, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901908 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901908 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901908 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901908 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901908 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901908, 45, 32);
DELETE FROM weenie_properties_int WHERE object_Id = 901908 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901908, 179, 64);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901908, 3964, 2), (901908, 4329, 2), (901908, 4638, 2), (901908, 5418, 2), (901908, 4596, 2), (901908, 4670, 2), (901908, 4705, 2), (901908, 4494, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901908, 0, 33495304);   -- 0x01FF1908

-- ---------------------------------------------------------------- 901909 Serpent's Judgment (clone of retail rare 42666 Decapitator's Blade; base setup 0x020018BB Nodachi)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901909, 'ace901909-serpentsjudgment', type, NOW() FROM weenie WHERE class_Id = 42666;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901909, type, value FROM weenie_properties_int WHERE object_Id = 42666;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901909, type, value FROM weenie_properties_int64 WHERE object_Id = 42666;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901909, type, value FROM weenie_properties_bool WHERE object_Id = 42666;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901909, type, value FROM weenie_properties_float WHERE object_Id = 42666;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901909, type, value FROM weenie_properties_d_i_d WHERE object_Id = 42666;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901909, type, value FROM weenie_properties_i_i_d WHERE object_Id = 42666;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901909, type, value FROM weenie_properties_string WHERE object_Id = 42666;
DELETE FROM weenie_properties_string WHERE object_Id = 901909 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901909, 1, 'Serpent''s Judgment');
DELETE FROM weenie_properties_string WHERE object_Id = 901909 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901909, 16, 'The last verdict Judge Fang ever wrote is carved along the fin of this blade, in a script no living scholar can read. It is heavy, as judgment should be.');
DELETE FROM weenie_properties_string WHERE object_Id = 901909 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901909 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901909, 1, 33560763);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901909 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901909, 8, 117381385);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901909 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901909, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901909 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901909 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901909 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901909 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 901909 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901909, 45, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901909 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901909, 179, 8);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901909, 3965, 2), (901909, 4400, 2), (901909, 5032, 2), (901909, 4596, 2), (901909, 4661, 2), (901909, 4682, 2), (901909, 5034, 2), (901909, 4395, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901909, 0, 33495305);   -- 0x01FF1909

-- ---------------------------------------------------------------- 901910 Serpent's Ascension (clone of retail rare 30303 Serpent's Flight; base setup 0x02001347 Serpent's Flight (bow))
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 901910, 'ace901910-serpentsascension', type, NOW() FROM weenie WHERE class_Id = 30303;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901910, type, value FROM weenie_properties_int WHERE object_Id = 30303;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901910, type, value FROM weenie_properties_int64 WHERE object_Id = 30303;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901910, type, value FROM weenie_properties_bool WHERE object_Id = 30303;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901910, type, value FROM weenie_properties_float WHERE object_Id = 30303;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901910, type, value FROM weenie_properties_d_i_d WHERE object_Id = 30303;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901910, type, value FROM weenie_properties_i_i_d WHERE object_Id = 30303;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901910, type, value FROM weenie_properties_string WHERE object_Id = 30303;
DELETE FROM weenie_properties_string WHERE object_Id = 901910 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901910, 1, 'Serpent''s Ascension');
DELETE FROM weenie_properties_string WHERE object_Id = 901910 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901910, 16, 'Judge Fang''s bow, shed and renewed. His students say that on the day he died the serpents of his bow drew breath, and that a scholar who brings them three skins may watch them rise. They have not stopped rising since.');
DELETE FROM weenie_properties_string WHERE object_Id = 901910 AND type IN (14, 15);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901910 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901910, 1, 33559367);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901910 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901910, 8, 117381386);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901910 AND type = 6;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901910, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901910 AND type = 52;   -- IconUnderlay: the rare's purple square; not a rare
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901910 AND type = 7;    -- ClothingBase: the rare model's own table; ours is the anim_part row, which ViridianArms only sends for a weapon with no ClothingBase (Serpent's Flight has none)
DELETE FROM weenie_properties_int WHERE object_Id = 901910 AND type = 17;   -- RareId: not a rare
DELETE FROM weenie_properties_float WHERE object_Id = 901910 AND type = 29;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901910, 29, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901910 AND type = 149;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901910, 149, 1.01);
DELETE FROM weenie_properties_float WHERE object_Id = 901910 AND type = 150;
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901910, 150, 1.01);
DELETE FROM weenie_properties_int WHERE object_Id = 901910 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901910, 45, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901910 AND type = 179;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901910, 179, 8);
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) VALUES (901910, 3963, 2), (901910, 4400, 2), (901910, 4522, 2), (901910, 4596, 2), (901910, 4661, 2), (901910, 4417, 2), (901910, 4713, 2), (901910, 5183, 2);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901910, 0, 33495306);   -- 0x01FF190A

-- ---------------------------------------------------------------- the Keeper of Lost Things (901000): sells all ten
DELETE FROM weenie_properties_create_list WHERE object_Id = 901000 AND destination_Type = 4 AND weenie_Class_Id BETWEEN 901900 AND 901949;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES
  (901000, 4, 901900, -1, 0, 0, 0),
  (901000, 4, 901901, -1, 0, 0, 0),
  (901000, 4, 901902, -1, 0, 0, 0),
  (901000, 4, 901903, -1, 0, 0, 0),
  (901000, 4, 901904, -1, 0, 0, 0),
  (901000, 4, 901905, -1, 0, 0, 0),
  (901000, 4, 901906, -1, 0, 0, 0),
  (901000, 4, 901907, -1, 0, 0, 0),
  (901000, 4, 901908, -1, 0, 0, 0),
  (901000, 4, 901909, -1, 0, 0, 0),
  (901000, 4, 901910, -1, 0, 0, 0);

COMMIT;
