-- SPREAD THE APPROVED MONSTERS (owner 2026-09-29). Generated by tools/gpubox-ace/spread_approved.py;
-- edit that and regenerate. New landblock_instance rows only, each an existing family generator.
--
-- Apply: ssh gpubox '~/Dereth-Unity/tools/gpubox-ace/apply-live.sh tools/gpubox-ace/spread-approved-monsters.sql 6F92 83A5 8CA3 8CAD 8EBB 91B9 9366 968F AA69 C4B4 CEB5 D37E D3A5 DF78 E06E F04F'
START TRANSACTION;
DELETE FROM landblock_instance WHERE guid IN (0x7E06EE80, 0x7DF78E80, 0x7D3A5E80, 0x783A5E80, 0x78CADE80, 0x791B9E80, 0x78CA3E80, 0x7C4B4E80, 0x7CEB5E80, 0x7F04FE80, 0x7968FE80, 0x7AA69E80, 0x79366E80, 0x78EBBE80, 0x76F92E80, 0x7D37EE80);
-- 901210: 13.4S 77.4E, the Dryreach strand (sand-grey)
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7E06EE80, 901210, 0xE06E000E, 36.0, 132.0, 0.0, 1, 0, 0, 0, 0);
-- 901210: 5.4S 76.9E, below Dry Beach Manors (sand-grey)
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7DF78E80, 901210, 0xDF780026, 108.0, 132.0, 0.0, 1, 0, 0, 0, 0);
-- 901210: 30.4N 66.9E, Cape Feirgard (sand-grey)
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7D3A5E80, 901210, 0xD3A50004, 12.0, 84.0, 0.0, 1, 0, 0, 0, 0);
-- 901270: 30.4N 3.4E, the forest west of the Arcanum Consortium
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x783A5E80, 901270, 0x83A5002C, 132.0, 84.0, 50.0, 1, 0, 0, 0, 0);
-- 901270: 36.9N 10.8E, the forest by A Ruin
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x78CADE80, 901270, 0x8CAD003D, 180.0, 108.0, 60.0, 1, 0, 0, 0, 0);
-- 901270: 46.7N 14.4E, the pines by Pine Hillock Settlement
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x791B9E80, 901270, 0x91B9001F, 84.0, 156.0, 47.5, 1, 0, 0, 0, 0);
-- 901270: 28.9N 10.3E, the forest south of the Consortium
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x78CA3E80, 901270, 0x8CA30015, 60.0, 108.0, 42.0, 1, 0, 0, 0, 0);
-- 901271: 42.1N 55.3E, the snowfield by the Ward Guardian Cave
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7C4B4E80, 901271, 0xC4B40021, 108.0, 12.0, 542.0, 1, 0, 0, 0, 0);
-- 901271: 42.9N 63.5E, the barren rock at the Misty Mine
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7CEB5E80, 901271, 0xCEB50031, 156.0, 12.0, 216.5, 1, 0, 0, 0, 0);
-- 901271: 38.2S 90.6E, the barren hills of Tou-Tou Valley
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7F04FE80, 901271, 0xF04F002E, 132.0, 132.0, 103.0, 1, 0, 0, 0, 0);
-- 901272: 12.5N 18.2E, the sand south-east of Al-Jalima
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7968FE80, 901272, 0x968F0009, 36.0, 12.0, 50.0, 1, 0, 0, 0, 0);
-- 901272: 17.7S 34.1E, the rock-strewn sand by Amiantos Bethel
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7AA69E80, 901272, 0xAA690003, 12.0, 60.0, 46.0, 1, 0, 0, 0, 0);
-- 901272: 19.9S 15.7E, the dunes north of Al-Arqas
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x79366E80, 901272, 0x93660005, 12.0, 108.0, 14.0, 1, 0, 0, 0, 0);
-- 901401: 47.8N 12.0E, the grass below the Eastham portal
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x78EBBE80, 901401, 0x8EBB001A, 84.0, 36.0, 126.0, 1, 0, 0, 0, 0);
-- 901401: 15.4N 12.8W, Hidden Valley
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x76F92E80, 901401, 0x6F92001E, 84.0, 132.0, 116.0, 1, 0, 0, 0, 0);
-- 901401: 1.1S 66.9E, the grass by Siege Road Settlement
INSERT INTO landblock_instance (guid, weenie_Class_Id, obj_Cell_Id, origin_X, origin_Y, origin_Z, angles_W, angles_X, angles_Y, angles_Z, is_Link_Child) VALUES (0x7D37EE80, 901401, 0xD37E0001, 12.0, 12.0, 20.0, 1, 0, 0, 0, 0);
COMMIT;
