-- THE VIRIDIAN TRADE-UP, live data (owner 2026-09-28: add it to the game). Generated by
-- tools/gpubox-ace/viridian_arms.py -- edit that, not this. Needs viridian-arms.sql first.
-- Backup of every row it touches: viridian-backup-2026-09-28.sql. Re-runnable.
--
--   Kervim'telek: GIVE him a Stormwood weapon. With Deru Heartwood Sap in your pack he takes one sap and
--     gives the Viridian weapon of the same family; without it he refunds amber exactly as retail did.
--   The four Viridian rare bosses each leave 3 Deru Heartwood Sap in their corpse.
--   Placeholder quest descriptions ("quest timer", "kill counter") get real text for the journal.
START TRANSACTION;

DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.quest LIKE 'ViridianTradeUp-%';
DELETE FROM weenie_properties_emote WHERE object_Id = 53271 AND quest LIKE 'ViridianTradeUp-%';

-- atlatl: Stormwood (53307, 72004) -> 900859 Waspsting Atlatl
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53307;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53307;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-atlatl', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53307;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 72004;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 72004;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-atlatl', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 72004;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-atlatl');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Waspsting Atlatl, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900859, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-atlatl');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- axe: Stormwood (53308, 53320) -> 900851 Heartwood Cleaver
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53308;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53308;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-axe', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53308;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53320;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53320;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-axe', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53320;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-axe');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Heartwood Cleaver, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900851, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-axe');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- bow: Stormwood (53309, 53321) -> 900857 Viridian Longbow
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53309;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53309;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-bow', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53309;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53321;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53321;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-bow', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53321;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-bow');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Viridian Longbow, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900857, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-bow');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- crossbow: Stormwood (53310, 53322) -> 900858 Briarwood Crossbow
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53310;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53310;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-crossbow', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53310;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53322;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53322;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-crossbow', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53322;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-crossbow');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Briarwood Crossbow, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900858, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-crossbow');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- mace: Stormwood (53312, 53324) -> 900852 Amberknot Mace
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53312;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53312;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-mace', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53312;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53324;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53324;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-mace', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53324;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-mace');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Amberknot Mace, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900852, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-mace');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- spear: Stormwood (53313, 53325) -> 900853 Thornroot Spear
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53313;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53313;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-spear', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53313;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53325;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53325;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-spear', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53325;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-spear');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Thornroot Spear, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900853, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-spear');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- staff: Stormwood (53314, 72005) -> 900855 Deru Rootstaff
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53314;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53314;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-staff', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53314;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 72005;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 72005;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-staff', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 72005;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-staff');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Deru Rootstaff, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900855, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-staff');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- greatsword: Stormwood (53315, 53327) -> 900861 Deru Greatblade
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53315;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53315;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-greatsword', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53315;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53327;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53327;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-greatsword', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53327;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-greatsword');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Deru Greatblade, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900861, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-greatsword');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- sword: Stormwood (53316, 53328) -> 900850 Deru Leafblade
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53316;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53316;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-sword', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53316;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53328;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53328;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-sword', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53328;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-sword');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Deru Leafblade, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900850, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-sword');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- claw: Stormwood (53317, 53329) -> 900856 Thornclaw
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53317;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53317;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-claw', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53317;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53329;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53329;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-claw', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53329;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-claw');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Thornclaw, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900856, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-claw');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- wand: Stormwood (53318, 53330) -> 900860 Amberheart Wand
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53318;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53318;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-wand', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53318;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53330;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53330;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-wand', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53330;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-wand');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Amberheart Wand, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900860, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-wand');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- dagger: Stormwood (53323, 72006) -> 900854 Sapling Fang
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 53323;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53323;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-dagger', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 53323;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 6 AND e.weenie_Class_Id = 72006;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent) SELECT id, 0, 12, 0, 1 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 72006;
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) SELECT id, 1, 76, 0, 1, 'ViridianTradeUp-dagger', 900863, 1, 0 FROM weenie_properties_emote WHERE object_Id = 53271 AND category = 6 AND weenie_Class_Id = 72006;
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 22, 1, 'ViridianTradeUp-dagger');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message, weenie_Class_Id, stack_Size, destination_Type) VALUES (@e, 0, 10, 0, 1, 'The heartwood sap takes to the Stormwood at once. Here, champion: the Sapling Fang, grown anew.', NULL, NULL, NULL), (@e, 1, 74, 0, 1, NULL, 900863, 1, 0), (@e, 2, 3, 0, 1, NULL, 900854, 1, 0);
INSERT INTO weenie_properties_emote (object_Id, category, probability, quest) VALUES (53271, 23, 1, 'ViridianTradeUp-dagger');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 10, 0, 1, 'You are not interested in my gift? Well then let us see how much amber survived the ritual.'), (@e, 1, 10, 0, 1, 'Had you brought me Deru Heartwood Sap, I could have grown this into something greater.'), (@e, 2, 67, 0, 1, 'refundAmber');

-- the sap handed over first: refused WITH directions (category 1 Refuse keeps it in the pack)
INSERT INTO weenie_properties_emote (object_Id, category, probability, weenie_Class_Id, quest) VALUES (53271, 1, 1, 900863, 'ViridianTradeUp-sapfirst');
SET @e = LAST_INSERT_ID();
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) VALUES (@e, 0, 12, 0, 1, NULL), (@e, 1, 10, 0, 1, 'Keep the sap in your pack, champion, and hand me the Stormwood weapon itself. I will draw the sap into it.');
-- and the offer at the end of his greeting (both Use sets)
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id = 53271 AND e.category = 7 AND a.message = 'If you carry Deru Heartwood Sap, hand me any Stormwood weapon and I will grow it into its Viridian kin.';
INSERT INTO weenie_properties_emote_action (emote_Id, `order`, type, delay, extent, message) SELECT e.id, (SELECT MAX(a.`order`) + 1 FROM weenie_properties_emote_action a WHERE a.emote_Id = e.id), 10, 0, 1, 'If you carry Deru Heartwood Sap, hand me any Stormwood weapon and I will grow it into its Viridian kin.' FROM weenie_properties_emote e WHERE e.object_Id = 53271 AND e.category = 7;

-- the rare bosses: 3 sap each, in the corpse like their essences (ContainTreasure, 100%)
DELETE FROM weenie_properties_create_list WHERE object_Id IN (53365, 72000, 72001, 72002) AND weenie_Class_Id = 900863;
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (53365, 9, 900863, 1, 0, 1, 0);   -- Wind Fury
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (53365, 9, 900863, 1, 0, 1, 0);   -- Wind Fury
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (53365, 9, 900863, 1, 0, 1, 0);   -- Wind Fury
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72000, 9, 900863, 1, 0, 1, 0);   -- NightBrier
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72000, 9, 900863, 1, 0, 1, 0);   -- NightBrier
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72000, 9, 900863, 1, 0, 1, 0);   -- NightBrier
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72001, 9, 900863, 1, 0, 1, 0);   -- Norshuntyr
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72001, 9, 900863, 1, 0, 1, 0);   -- Norshuntyr
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72001, 9, 900863, 1, 0, 1, 0);   -- Norshuntyr
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72002, 9, 900863, 1, 0, 1, 0);   -- Zerzelikyr
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72002, 9, 900863, 1, 0, 1, 0);   -- Zerzelikyr
INSERT INTO weenie_properties_create_list (object_Id, destination_Type, weenie_Class_Id, stack_Size, palette, shade, try_To_Bond) VALUES (72002, 9, 900863, 1, 0, 1, 0);   -- Zerzelikyr

-- journal text
UPDATE quest SET message = 'Menhir Ring: you woke the Oak guardian (1 of 10). Next: Hickory.' WHERE name = 'viridianRitual1';
UPDATE quest SET message = 'Menhir Ring: you woke the Hickory guardian (2 of 10). Next: Birch.' WHERE name = 'viridianRitual2';
UPDATE quest SET message = 'Menhir Ring: you woke the Birch guardian (3 of 10). Next: Willow.' WHERE name = 'viridianRitual3';
UPDATE quest SET message = 'Menhir Ring: you woke the Willow guardian (4 of 10). Next: Maple.' WHERE name = 'viridianRitual4';
UPDATE quest SET message = 'Menhir Ring: you woke the Maple guardian (5 of 10). Next: Cedar.' WHERE name = 'viridianRitual5';
UPDATE quest SET message = 'Menhir Ring: you woke the Cedar guardian (6 of 10). Next: Pine.' WHERE name = 'viridianRitual6';
UPDATE quest SET message = 'Menhir Ring: you woke the Pine guardian (7 of 10). Next: Spruce.' WHERE name = 'viridianRitual7';
UPDATE quest SET message = 'Menhir Ring: you woke the Spruce guardian (8 of 10). Next: Yew.' WHERE name = 'viridianRitual8';
UPDATE quest SET message = 'Menhir Ring: you woke the Yew guardian (9 of 10). Next: Ash.' WHERE name = 'viridianRitual9';
UPDATE quest SET message = 'Menhir Ring ritual complete. The Ancient Statue will open the way into the Viridian Rise.' WHERE name = 'viridianFlag';
UPDATE quest SET message = 'Menhir Ring: a guardian was woken out of order. Begin again: Oak, Hickory, Birch, Willow, Maple, Cedar, Pine, Spruce, Yew, Ash.' WHERE name = 'viridianFail';
UPDATE quest SET message = 'The Ancient Statue of the Menhir Ring is gathering its power again.' WHERE name = 'viridianRecharge';
UPDATE quest SET message = 'You climbed the Viridian Deru Tree and spoke with Doriathazaar.' WHERE name = 'ClimbedViridianDeru';
UPDATE quest SET message = 'Brier Wasps slain for Aangesilus' WHERE name = 'KilltaskViridianWasp';
UPDATE quest SET message = 'A''nekshen slain for Brellegia' WHERE name = 'KilltaskViridianAnek';
UPDATE quest SET message = 'Zefir slain for Swift' WHERE name = 'KilltaskViridianZefir';
UPDATE quest SET message = 'Aangesilus has no new wasp task for you yet.' WHERE name = 'KilltaskViridianWaspWait';
UPDATE quest SET message = 'Brellegia has no new A''nekshen task for you yet.' WHERE name = 'KilltaskViridianAnekWait';
UPDATE quest SET message = 'Swift has no new Zefir task for you yet.' WHERE name = 'KilltaskViridianZefirWait';

COMMIT;
