-- THE VIRIDIAN ARMS, weenies 900850-900862 (owner, 2026-09-28: "a new weapon set for viridian rise").
-- MADE, NOT APPLIED. Generated by tools/gpubox-ace/viridian_arms.py -- edit that, not this.
-- Design and numbers: docs/VIRIDIAN-RISE-UPGRADE.md. Art: expansion/weapons/viridian/.
--
-- Each weapon clones its retail Stormwood sibling (the Infused Amber Collection's reward, wield 430
-- melee / 385 missile and caster) and changes only: name, descriptions, icon, setup, ObjScale,
-- damage type, EquipmentSetId 900, and one anim_part row (index 0 -> our GfxObj). No emote gives
-- them yet; @ci <wcid> on a staging shard to look at one.
--
--   ssh gpubox sudo -n mysql ace_world_staging < tools/gpubox-ace/viridian-arms.sql     (staging)
--   then @clearcache weenie. Server side needs RevivalGuard ViridianArms for the held model and the
--   set bonus; both properties default OFF (expansion_weapon_parts, viridian_set_bonus).
START TRANSACTION;

DELETE FROM weenie_properties_int WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_int64 WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_bool WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_float WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_d_i_d WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_i_i_d WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_string WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_spell_book WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie_properties_anim_part WHERE object_Id BETWEEN 900850 AND 900899;
DELETE FROM weenie WHERE class_Id BETWEEN 900850 AND 900899;

-- ---------------------------------------------------------------- 900850 Deru Leafblade (clone of retail 53328, base setup 0x02000065 Long Sword)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900850, 'ace900850-deruleafblade', type, NOW() FROM weenie WHERE class_Id = 53328;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900850, type, value FROM weenie_properties_int WHERE object_Id = 53328;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900850, type, value FROM weenie_properties_int64 WHERE object_Id = 53328;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900850, type, value FROM weenie_properties_bool WHERE object_Id = 53328;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900850, type, value FROM weenie_properties_float WHERE object_Id = 53328;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900850, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53328;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900850, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53328;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900850, type, value FROM weenie_properties_string WHERE object_Id = 53328;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900850, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53328;
DELETE FROM weenie_properties_string WHERE object_Id = 900850 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900850, 1, 'Deru Leafblade');
DELETE FROM weenie_properties_string WHERE object_Id = 900850 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900850, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900850 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900850, 16, 'A blade grown, not forged: a single Deru leaf hardened in amber sap on a root hilt.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900850 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900850, 1, 33554533);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900850 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900850, 8, 117377104);
DELETE FROM weenie_properties_float WHERE object_Id = 900850 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900850 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900850, 45, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 900850 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900850, 265, 900);
DELETE FROM weenie_properties_int WHERE object_Id = 900850 AND type = 49;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900850, 49, 40);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900850, 0, 33491024);   -- 0x01FF0850

-- ---------------------------------------------------------------- 900851 Heartwood Cleaver (clone of retail 53320, base setup 0x02000125 Battle Axe)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900851, 'ace900851-heartwoodcleaver', type, NOW() FROM weenie WHERE class_Id = 53320;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900851, type, value FROM weenie_properties_int WHERE object_Id = 53320;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900851, type, value FROM weenie_properties_int64 WHERE object_Id = 53320;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900851, type, value FROM weenie_properties_bool WHERE object_Id = 53320;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900851, type, value FROM weenie_properties_float WHERE object_Id = 53320;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900851, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53320;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900851, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53320;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900851, type, value FROM weenie_properties_string WHERE object_Id = 53320;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900851, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53320;
DELETE FROM weenie_properties_string WHERE object_Id = 900851 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900851, 1, 'Heartwood Cleaver');
DELETE FROM weenie_properties_string WHERE object_Id = 900851 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900851, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900851 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900851, 16, 'A broad Deru leaf set in a heartwood haft, its edge honed like the canopy''s in a storm.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900851 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900851, 1, 33554725);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900851 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900851, 8, 117377105);
DELETE FROM weenie_properties_float WHERE object_Id = 900851 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900851 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900851, 45, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 900851 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900851, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900851, 0, 33491025);   -- 0x01FF0851

-- ---------------------------------------------------------------- 900852 Amberknot Mace (clone of retail 53324, base setup 0x0200013A Mace)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900852, 'ace900852-amberknotmace', type, NOW() FROM weenie WHERE class_Id = 53324;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900852, type, value FROM weenie_properties_int WHERE object_Id = 53324;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900852, type, value FROM weenie_properties_int64 WHERE object_Id = 53324;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900852, type, value FROM weenie_properties_bool WHERE object_Id = 53324;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900852, type, value FROM weenie_properties_float WHERE object_Id = 53324;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900852, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53324;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900852, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53324;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900852, type, value FROM weenie_properties_string WHERE object_Id = 53324;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900852, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53324;
DELETE FROM weenie_properties_string WHERE object_Id = 900852 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900852, 1, 'Amberknot Mace');
DELETE FROM weenie_properties_string WHERE object_Id = 900852 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900852, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900852 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900852, 16, 'A burl of Deru root studded with amber knots and the thorns that guard them.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900852 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900852, 1, 33554746);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900852 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900852, 8, 117377106);
DELETE FROM weenie_properties_float WHERE object_Id = 900852 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900852 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900852, 45, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 900852 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900852, 265, 900);
UPDATE weenie_properties_spell_book SET spell = 4518 WHERE object_Id = 900852 AND spell = 4624;   -- the family's own mastery
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900852, 0, 33491026);   -- 0x01FF0852

-- ---------------------------------------------------------------- 900853 Thornroot Spear (clone of retail 53325, base setup 0x02000144 Spear)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900853, 'ace900853-thornrootspear', type, NOW() FROM weenie WHERE class_Id = 53325;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900853, type, value FROM weenie_properties_int WHERE object_Id = 53325;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900853, type, value FROM weenie_properties_int64 WHERE object_Id = 53325;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900853, type, value FROM weenie_properties_bool WHERE object_Id = 53325;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900853, type, value FROM weenie_properties_float WHERE object_Id = 53325;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900853, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53325;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900853, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53325;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900853, type, value FROM weenie_properties_string WHERE object_Id = 53325;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900853, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53325;
DELETE FROM weenie_properties_string WHERE object_Id = 900853 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900853, 1, 'Thornroot Spear');
DELETE FROM weenie_properties_string WHERE object_Id = 900853 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900853, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900853 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900853, 16, 'A straight Deru shoot, hardened in sap, tipped with a leaf and barbed with thorn.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900853 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900853, 1, 33554756);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900853 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900853, 8, 117377107);
DELETE FROM weenie_properties_float WHERE object_Id = 900853 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900853 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900853, 45, 2);
DELETE FROM weenie_properties_int WHERE object_Id = 900853 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900853, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900853, 0, 33491027);   -- 0x01FF0853

-- ---------------------------------------------------------------- 900854 Sapling Fang (clone of retail 53323, base setup 0x0200012F Dagger)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900854, 'ace900854-saplingfang', type, NOW() FROM weenie WHERE class_Id = 53323;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900854, type, value FROM weenie_properties_int WHERE object_Id = 53323;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900854, type, value FROM weenie_properties_int64 WHERE object_Id = 53323;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900854, type, value FROM weenie_properties_bool WHERE object_Id = 53323;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900854, type, value FROM weenie_properties_float WHERE object_Id = 53323;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900854, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53323;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900854, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53323;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900854, type, value FROM weenie_properties_string WHERE object_Id = 53323;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900854, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53323;
DELETE FROM weenie_properties_string WHERE object_Id = 900854 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900854, 1, 'Sapling Fang');
DELETE FROM weenie_properties_string WHERE object_Id = 900854 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900854, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900854 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900854, 16, 'A curved leaf-fang from a Deru sapling, still putting out leaves at the hilt.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900854 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900854, 1, 33554735);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900854 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900854, 8, 117377108);
DELETE FROM weenie_properties_float WHERE object_Id = 900854 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900854 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900854, 45, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 900854 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900854, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900854, 0, 33491028);   -- 0x01FF0854

-- ---------------------------------------------------------------- 900855 Deru Rootstaff (clone of retail 72005, base setup 0x0200013D Quarter Staff)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900855, 'ace900855-derurootstaff', type, NOW() FROM weenie WHERE class_Id = 72005;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900855, type, value FROM weenie_properties_int WHERE object_Id = 72005;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900855, type, value FROM weenie_properties_int64 WHERE object_Id = 72005;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900855, type, value FROM weenie_properties_bool WHERE object_Id = 72005;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900855, type, value FROM weenie_properties_float WHERE object_Id = 72005;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900855, type, value FROM weenie_properties_d_i_d WHERE object_Id = 72005;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900855, type, value FROM weenie_properties_i_i_d WHERE object_Id = 72005;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900855, type, value FROM weenie_properties_string WHERE object_Id = 72005;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900855, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 72005;
DELETE FROM weenie_properties_string WHERE object_Id = 900855 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900855, 1, 'Deru Rootstaff');
DELETE FROM weenie_properties_string WHERE object_Id = 900855 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900855, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900855 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900855, 16, 'A crooked length of Deru root whose crown has closed around a heart of amber.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900855 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900855, 1, 33554749);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900855 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900855, 8, 117377109);
DELETE FROM weenie_properties_float WHERE object_Id = 900855 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900855 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900855, 45, 4);
DELETE FROM weenie_properties_int WHERE object_Id = 900855 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900855, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900855, 0, 33491029);   -- 0x01FF0855

-- ---------------------------------------------------------------- 900856 Thornclaw (clone of retail 53329, base setup 0x02000137 Katar)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900856, 'ace900856-thornclaw', type, NOW() FROM weenie WHERE class_Id = 53329;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900856, type, value FROM weenie_properties_int WHERE object_Id = 53329;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900856, type, value FROM weenie_properties_int64 WHERE object_Id = 53329;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900856, type, value FROM weenie_properties_bool WHERE object_Id = 53329;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900856, type, value FROM weenie_properties_float WHERE object_Id = 53329;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900856, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53329;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900856, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53329;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900856, type, value FROM weenie_properties_string WHERE object_Id = 53329;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900856, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53329;
DELETE FROM weenie_properties_string WHERE object_Id = 900856 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900856, 1, 'Thornclaw');
DELETE FROM weenie_properties_string WHERE object_Id = 900856 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900856, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900856 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900856, 16, 'Three thorn-blades on a bark frame, worn over the fist like the Rise''s own claws.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900856 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900856, 1, 33554743);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900856 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900856, 8, 117377110);
DELETE FROM weenie_properties_float WHERE object_Id = 900856 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900856 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900856, 45, 3);
DELETE FROM weenie_properties_int WHERE object_Id = 900856 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900856, 265, 900);
UPDATE weenie_properties_spell_book SET spell = 4538 WHERE object_Id = 900856 AND spell = 4624;   -- the family's own mastery
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900856, 0, 33491030);   -- 0x01FF0856

-- ---------------------------------------------------------------- 900857 Viridian Longbow (clone of retail 53321, base setup 0x02000DC7 Lautaloi (bow))
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900857, 'ace900857-viridianlongbow', type, NOW() FROM weenie WHERE class_Id = 53321;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900857, type, value FROM weenie_properties_int WHERE object_Id = 53321;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900857, type, value FROM weenie_properties_int64 WHERE object_Id = 53321;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900857, type, value FROM weenie_properties_bool WHERE object_Id = 53321;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900857, type, value FROM weenie_properties_float WHERE object_Id = 53321;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900857, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53321;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900857, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53321;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900857, type, value FROM weenie_properties_string WHERE object_Id = 53321;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900857, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53321;
DELETE FROM weenie_properties_string WHERE object_Id = 900857 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900857, 1, 'Viridian Longbow');
DELETE FROM weenie_properties_string WHERE object_Id = 900857 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900857, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900857 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900857, 16, 'A recurved bow of living Deru wood. Arrows loosed from it carry the amber''s sting.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900857 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900857, 1, 33557959);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900857 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900857, 8, 117377111);
DELETE FROM weenie_properties_float WHERE object_Id = 900857 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900857 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900857, 45, 32);
DELETE FROM weenie_properties_int WHERE object_Id = 900857 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900857, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900857, 0, 33491031);   -- 0x01FF0857

-- ---------------------------------------------------------------- 900858 Briarwood Crossbow (clone of retail 53322, base setup 0x0200134C Zefir's Breath (crossbow))
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900858, 'ace900858-briarwoodcrossbow', type, NOW() FROM weenie WHERE class_Id = 53322;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900858, type, value FROM weenie_properties_int WHERE object_Id = 53322;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900858, type, value FROM weenie_properties_int64 WHERE object_Id = 53322;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900858, type, value FROM weenie_properties_bool WHERE object_Id = 53322;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900858, type, value FROM weenie_properties_float WHERE object_Id = 53322;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900858, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53322;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900858, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53322;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900858, type, value FROM weenie_properties_string WHERE object_Id = 53322;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900858, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53322;
DELETE FROM weenie_properties_string WHERE object_Id = 900858 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900858, 1, 'Briarwood Crossbow');
DELETE FROM weenie_properties_string WHERE object_Id = 900858 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900858, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900858 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900858, 16, 'A briarwood crossbow on a heartwood stock. Its bolts carry the amber''s sting.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900858 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900858, 1, 33559372);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900858 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900858, 8, 117377112);
DELETE FROM weenie_properties_float WHERE object_Id = 900858 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900858 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900858, 45, 32);
DELETE FROM weenie_properties_int WHERE object_Id = 900858 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900858, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900858, 0, 33491032);   -- 0x01FF0858

-- ---------------------------------------------------------------- 900859 Waspsting Atlatl (clone of retail 72004, base setup 0x02000BB9 Atlatl)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900859, 'ace900859-waspstingatlatl', type, NOW() FROM weenie WHERE class_Id = 72004;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900859, type, value FROM weenie_properties_int WHERE object_Id = 72004;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900859, type, value FROM weenie_properties_int64 WHERE object_Id = 72004;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900859, type, value FROM weenie_properties_bool WHERE object_Id = 72004;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900859, type, value FROM weenie_properties_float WHERE object_Id = 72004;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900859, type, value FROM weenie_properties_d_i_d WHERE object_Id = 72004;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900859, type, value FROM weenie_properties_i_i_d WHERE object_Id = 72004;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900859, type, value FROM weenie_properties_string WHERE object_Id = 72004;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900859, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 72004;
DELETE FROM weenie_properties_string WHERE object_Id = 900859 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900859, 1, 'Waspsting Atlatl');
DELETE FROM weenie_properties_string WHERE object_Id = 900859 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900859, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900859 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900859, 16, 'A carved Deru spear-thrower with a wasp-sting spur of amber. Its darts carry the sting.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900859 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900859, 1, 33557433);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900859 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900859, 8, 117377113);
DELETE FROM weenie_properties_float WHERE object_Id = 900859 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900859 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900859, 45, 32);
DELETE FROM weenie_properties_int WHERE object_Id = 900859 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900859, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900859, 0, 33491033);   -- 0x01FF0859

-- ---------------------------------------------------------------- 900860 Amberheart Wand (clone of retail 53330, base setup 0x0200017C Wand)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900860, 'ace900860-amberheartwand', type, NOW() FROM weenie WHERE class_Id = 53330;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900860, type, value FROM weenie_properties_int WHERE object_Id = 53330;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900860, type, value FROM weenie_properties_int64 WHERE object_Id = 53330;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900860, type, value FROM weenie_properties_bool WHERE object_Id = 53330;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900860, type, value FROM weenie_properties_float WHERE object_Id = 53330;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900860, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53330;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900860, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53330;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900860, type, value FROM weenie_properties_string WHERE object_Id = 53330;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900860, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53330;
DELETE FROM weenie_properties_string WHERE object_Id = 900860 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900860, 1, 'Amberheart Wand');
DELETE FROM weenie_properties_string WHERE object_Id = 900860 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900860, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900860 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900860, 16, 'A twist of Deru root cradling a drop of amber that has not yet set.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900860 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900860, 1, 33554812);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900860 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900860, 8, 117377114);
DELETE FROM weenie_properties_float WHERE object_Id = 900860 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900860 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900860, 45, 32);
DELETE FROM weenie_properties_int WHERE object_Id = 900860 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900860, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900860, 0, 33491034);   -- 0x01FF085A

-- ---------------------------------------------------------------- 900861 Deru Greatblade (clone of retail 53327, base setup 0x020018BB Nodachi)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900861, 'ace900861-derugreatblade', type, NOW() FROM weenie WHERE class_Id = 53327;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900861, type, value FROM weenie_properties_int WHERE object_Id = 53327;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900861, type, value FROM weenie_properties_int64 WHERE object_Id = 53327;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900861, type, value FROM weenie_properties_bool WHERE object_Id = 53327;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900861, type, value FROM weenie_properties_float WHERE object_Id = 53327;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900861, type, value FROM weenie_properties_d_i_d WHERE object_Id = 53327;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900861, type, value FROM weenie_properties_i_i_d WHERE object_Id = 53327;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900861, type, value FROM weenie_properties_string WHERE object_Id = 53327;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900861, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 53327;
DELETE FROM weenie_properties_string WHERE object_Id = 900861 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900861, 1, 'Deru Greatblade');
DELETE FROM weenie_properties_string WHERE object_Id = 900861 AND type = 14;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900861, 14, 'This item may be tinkered and imbued like any loot-generated weapon.');
DELETE FROM weenie_properties_string WHERE object_Id = 900861 AND type = 16;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900861, 16, 'A Deru leaf grown to the length of a man, fanned with leaves at the guard and toothed with thorn.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900861 AND type = 1;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900861, 1, 33560763);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900861 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900861, 8, 117377115);
DELETE FROM weenie_properties_float WHERE object_Id = 900861 AND type = 39;   -- DefaultScale: modelled at size
DELETE FROM weenie_properties_int WHERE object_Id = 900861 AND type = 45;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900861, 45, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 900861 AND type = 265;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900861, 265, 900);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (900861, 0, 33491035);   -- 0x01FF085B

-- ---------------------------------------------------------------- 900862 Heartseed of the Deru (the set's trinket)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) VALUES (900862, 'ace900862-heartseedofthederu', 1, NOW());
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 1, 8);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 5, 50);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 9, 67108864);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 16, 1);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 19, 5000);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 93, 1044);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 265, 900);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 105, 8);
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900862, 131, 75);
INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900862, 39, 1.0);
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900862, 1, 33554680);
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900862, 8, 117377116);
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900862, 22, 872415275);
INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (900862, 22, 1);   -- Inscribable
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900862, 1, 'Heartseed of the Deru');
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900862, 14, 'Worn with any of the Viridian Arms, the Heartseed wakes the set: Viridian Grove Set.');
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900862, 16, 'A seed of the Deru tree, sealed in amber before it could sprout.');

-- ---------------------------------------------------------------- 900863 Deru Heartwood Sap (the trade-up token; clone of retail 52970 Viridian Essence)
INSERT INTO weenie (class_Id, class_Name, type, last_Modified) SELECT 900863, 'ace900863-deruheartwoodsap', type, NOW() FROM weenie WHERE class_Id = 52970;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900863, type, value FROM weenie_properties_int WHERE object_Id = 52970;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900863, type, value FROM weenie_properties_int64 WHERE object_Id = 52970;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900863, type, value FROM weenie_properties_bool WHERE object_Id = 52970;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900863, type, value FROM weenie_properties_float WHERE object_Id = 52970;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900863, type, value FROM weenie_properties_d_i_d WHERE object_Id = 52970;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900863, type, value FROM weenie_properties_i_i_d WHERE object_Id = 52970;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900863, type, value FROM weenie_properties_string WHERE object_Id = 52970;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 900863, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 52970;
DELETE FROM weenie_properties_string WHERE object_Id = 900863 AND type = 1;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900863, 1, 'Deru Heartwood Sap');
DELETE FROM weenie_properties_string WHERE object_Id = 900863 AND type = 15;
INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900863, 15, 'Sap from the heart of a Deru tree, drawn out when one of its corrupted guardians falls. Kervim''telek can set it into a Stormwood weapon to make one of the Viridian Arms.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900863 AND type = 8;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900863, 8, 117377117);
DELETE FROM weenie_properties_int WHERE object_Id = 900863 AND type IN (33, 114);   -- not Bonded, not Attuned: fellows can share a boss's sap
DELETE FROM weenie_properties_int WHERE object_Id = 900863 AND type = 19;
INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900863, 19, 100);

COMMIT;
