-- THE WARDENFORGED PLATE, weenies 901350-901360 (docs/ARMOR-SET.md).
-- GENERATED by tools/gpubox-ace/wardenforged_plate.py -- edit that, not this.
-- MADE, NOT ADDED: not applied to any database as of 2026-09-28. New rows only; nothing retail is
-- changed. Re-runnable: it deletes its own rows (901350-901399) first.
START TRANSACTION;

DELETE FROM weenie_properties_int WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_int64 WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_bool WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_float WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_string WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_d_i_d WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_i_i_d WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_palette WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_texture_map WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_anim_part WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_spell_book WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_create_list WHERE object_Id BETWEEN 901350 AND 901399;
DELETE a FROM weenie_properties_emote_action a JOIN weenie_properties_emote e ON e.id = a.emote_Id WHERE e.object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie_properties_emote WHERE object_Id BETWEEN 901350 AND 901399;
DELETE FROM weenie WHERE class_Id BETWEEN 901350 AND 901399;

-- ---------------------------------------------------------------- THE NINE PIECES
-- AL 540, protections slash/pierce/bludgeon 1.6, fire and lightning 1.8, cold and acid 1.2, nether 1.0;
-- unenchantable (ResistMagic 9999, as Covenant and Shadow armour); wield level 150; Bonded; set 901.
-- Worn meshes expansion/models/0x01FF1350-0x01FF1360.glb, dropped models w901350-w901358.glb, icons
-- expansion/textures/0x06FF1350-0x06FF1358.png. IgnoreCloIcons (bool 84) or the ClothingTable stamps
-- Covenant's icon over ours.
-- 901350 <- clone of 21156
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901350, 'ace901350-wardenforgedhelm', type FROM weenie WHERE class_Id = 21156;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901350, type, value FROM weenie_properties_int WHERE object_Id = 21156;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901350, type, value FROM weenie_properties_int64 WHERE object_Id = 21156;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901350, type, value FROM weenie_properties_bool WHERE object_Id = 21156;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901350, type, value FROM weenie_properties_float WHERE object_Id = 21156;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901350, type, value FROM weenie_properties_string WHERE object_Id = 21156;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901350, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21156;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901350, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21156;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901350, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21156;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901350, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21156;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901350, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21156;
DELETE FROM weenie_properties_string WHERE object_Id = 901350 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901350, 1, 'Wardenforged Helm');
DELETE FROM weenie_properties_string WHERE object_Id = 901350 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901350, 16, 'A closed helm with a swept crest. Aetherium burns behind the visor. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901350 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901350 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901350, 8, 117379920);
DELETE FROM weenie_properties_bool WHERE object_Id = 901350 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901350, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901350, 19, 18000);
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901350, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901350 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901350, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901350, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901350, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901350, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901350, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901350 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901350, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901350, 16, 33493840);  -- part 16 -> 0x01ff1350

-- 901351 <- clone of 21152
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901351, 'ace901351-wardenforgedbreastplate', type FROM weenie WHERE class_Id = 21152;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901351, type, value FROM weenie_properties_int WHERE object_Id = 21152;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901351, type, value FROM weenie_properties_int64 WHERE object_Id = 21152;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901351, type, value FROM weenie_properties_bool WHERE object_Id = 21152;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901351, type, value FROM weenie_properties_float WHERE object_Id = 21152;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901351, type, value FROM weenie_properties_string WHERE object_Id = 21152;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901351, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21152;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901351, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21152;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901351, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21152;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901351, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21152;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901351, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21152;
DELETE FROM weenie_properties_string WHERE object_Id = 901351 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901351, 1, 'Wardenforged Breastplate');
DELETE FROM weenie_properties_string WHERE object_Id = 901351 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901351, 16, 'The Warden''s sigil is set over the heart. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901351 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901351 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901351, 8, 117379921);
DELETE FROM weenie_properties_bool WHERE object_Id = 901351 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901351, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901351, 19, 30000);
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901351, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901351 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901351, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901351, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901351, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901351, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901351, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901351 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901351, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901351, 9, 33493841);  -- part 9 -> 0x01ff1351

-- 901352 <- clone of 21154
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901352, 'ace901352-wardenforgedgirth', type FROM weenie WHERE class_Id = 21154;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901352, type, value FROM weenie_properties_int WHERE object_Id = 21154;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901352, type, value FROM weenie_properties_int64 WHERE object_Id = 21154;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901352, type, value FROM weenie_properties_bool WHERE object_Id = 21154;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901352, type, value FROM weenie_properties_float WHERE object_Id = 21154;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901352, type, value FROM weenie_properties_string WHERE object_Id = 21154;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901352, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21154;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901352, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21154;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901352, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21154;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901352, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21154;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901352, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21154;
DELETE FROM weenie_properties_string WHERE object_Id = 901352 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901352, 1, 'Wardenforged Girth');
DELETE FROM weenie_properties_string WHERE object_Id = 901352 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901352, 16, 'A rune-cut belt over hooped faulds and riveted mail. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901352 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901352 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901352, 8, 117379922);
DELETE FROM weenie_properties_bool WHERE object_Id = 901352 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901352, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901352, 19, 20000);
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901352, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901352 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901352, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901352, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901352, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901352, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901352, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901352 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901352, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901352, 0, 33493842);  -- part 0 -> 0x01ff1352

-- 901353 <- clone of 21157
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901353, 'ace901353-wardenforgedpauldrons', type FROM weenie WHERE class_Id = 21157;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901353, type, value FROM weenie_properties_int WHERE object_Id = 21157;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901353, type, value FROM weenie_properties_int64 WHERE object_Id = 21157;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901353, type, value FROM weenie_properties_bool WHERE object_Id = 21157;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901353, type, value FROM weenie_properties_float WHERE object_Id = 21157;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901353, type, value FROM weenie_properties_string WHERE object_Id = 21157;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901353, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21157;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901353, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21157;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901353, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21157;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901353, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21157;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901353, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21157;
DELETE FROM weenie_properties_string WHERE object_Id = 901353 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901353, 1, 'Wardenforged Pauldrons');
DELETE FROM weenie_properties_string WHERE object_Id = 901353 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901353, 16, 'Three silver lames step down from each crystal-set shoulder. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901353 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901353 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901353, 8, 117379923);
DELETE FROM weenie_properties_bool WHERE object_Id = 901353 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901353, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901353, 19, 20000);
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901353, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901353 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901353, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901353, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901353, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901353, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901353, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901353 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901353, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901353, 10, 33493843);  -- part 10 -> 0x01ff1353
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901353, 13, 33493844);  -- part 13 -> 0x01ff1354

-- 901354 <- clone of 21151
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901354, 'ace901354-wardenforgedbracers', type FROM weenie WHERE class_Id = 21151;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901354, type, value FROM weenie_properties_int WHERE object_Id = 21151;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901354, type, value FROM weenie_properties_int64 WHERE object_Id = 21151;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901354, type, value FROM weenie_properties_bool WHERE object_Id = 21151;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901354, type, value FROM weenie_properties_float WHERE object_Id = 21151;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901354, type, value FROM weenie_properties_string WHERE object_Id = 21151;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901354, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21151;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901354, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21151;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901354, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21151;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901354, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21151;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901354, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21151;
DELETE FROM weenie_properties_string WHERE object_Id = 901354 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901354, 1, 'Wardenforged Bracers');
DELETE FROM weenie_properties_string WHERE object_Id = 901354 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901354, 16, 'Vambraces with pointed silver couters. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901354 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901354 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901354, 8, 117379924);
DELETE FROM weenie_properties_bool WHERE object_Id = 901354 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901354, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901354, 19, 15000);
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901354, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901354 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901354, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901354, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901354, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901354, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901354, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901354 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901354, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901354, 11, 33493845);  -- part 11 -> 0x01ff1355
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901354, 14, 33493846);  -- part 14 -> 0x01ff1356

-- 901355 <- clone of 21153
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901355, 'ace901355-wardenforgedgauntlets', type FROM weenie WHERE class_Id = 21153;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901355, type, value FROM weenie_properties_int WHERE object_Id = 21153;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901355, type, value FROM weenie_properties_int64 WHERE object_Id = 21153;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901355, type, value FROM weenie_properties_bool WHERE object_Id = 21153;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901355, type, value FROM weenie_properties_float WHERE object_Id = 21153;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901355, type, value FROM weenie_properties_string WHERE object_Id = 21153;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901355, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21153;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901355, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21153;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901355, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21153;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901355, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21153;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901355, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21153;
DELETE FROM weenie_properties_string WHERE object_Id = 901355 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901355, 1, 'Wardenforged Gauntlets');
DELETE FROM weenie_properties_string WHERE object_Id = 901355 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901355, 16, 'A crystal rides the back of each hand. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901355 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901355 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901355, 8, 117379925);
DELETE FROM weenie_properties_bool WHERE object_Id = 901355 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901355, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901355, 19, 15000);
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901355, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901355 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901355, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901355, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901355, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901355, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901355, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901355 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901355, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901355, 12, 33493847);  -- part 12 -> 0x01ff1357
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901355, 15, 33493848);  -- part 15 -> 0x01ff1358

-- 901356 <- clone of 21159
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901356, 'ace901356-wardenforgedtassets', type FROM weenie WHERE class_Id = 21159;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901356, type, value FROM weenie_properties_int WHERE object_Id = 21159;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901356, type, value FROM weenie_properties_int64 WHERE object_Id = 21159;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901356, type, value FROM weenie_properties_bool WHERE object_Id = 21159;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901356, type, value FROM weenie_properties_float WHERE object_Id = 21159;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901356, type, value FROM weenie_properties_string WHERE object_Id = 21159;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901356, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21159;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901356, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21159;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901356, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21159;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901356, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21159;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901356, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21159;
DELETE FROM weenie_properties_string WHERE object_Id = 901356 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901356, 1, 'Wardenforged Tassets');
DELETE FROM weenie_properties_string WHERE object_Id = 901356 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901356, 16, 'Cuisses under two hanging silver tassets. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901356 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901356 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901356, 8, 117379926);
DELETE FROM weenie_properties_bool WHERE object_Id = 901356 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901356, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901356, 19, 15000);
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901356, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901356 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901356, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901356, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901356, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901356, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901356, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901356 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901356, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901356, 1, 33493849);  -- part 1 -> 0x01ff1359
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901356, 5, 33493850);  -- part 5 -> 0x01ff135a

-- 901357 <- clone of 21155
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901357, 'ace901357-wardenforgedgreaves', type FROM weenie WHERE class_Id = 21155;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901357, type, value FROM weenie_properties_int WHERE object_Id = 21155;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901357, type, value FROM weenie_properties_int64 WHERE object_Id = 21155;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901357, type, value FROM weenie_properties_bool WHERE object_Id = 21155;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901357, type, value FROM weenie_properties_float WHERE object_Id = 21155;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901357, type, value FROM weenie_properties_string WHERE object_Id = 21155;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901357, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21155;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901357, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21155;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901357, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21155;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901357, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21155;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901357, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21155;
DELETE FROM weenie_properties_string WHERE object_Id = 901357 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901357, 1, 'Wardenforged Greaves');
DELETE FROM weenie_properties_string WHERE object_Id = 901357 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901357, 16, 'A keel runs down each shin from a crystal-set knee. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901357 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901357 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901357, 8, 117379927);
DELETE FROM weenie_properties_bool WHERE object_Id = 901357 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901357, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901357, 19, 15000);
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901357, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901357 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901357, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901357, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901357, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901357, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901357, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901357 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901357, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901357, 2, 33493851);  -- part 2 -> 0x01ff135b
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901357, 6, 33493852);  -- part 6 -> 0x01ff135c

-- 901358 <- clone of 21150
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901358, 'ace901358-wardenforgedsollerets', type FROM weenie WHERE class_Id = 21150;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901358, type, value FROM weenie_properties_int WHERE object_Id = 21150;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901358, type, value FROM weenie_properties_int64 WHERE object_Id = 21150;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901358, type, value FROM weenie_properties_bool WHERE object_Id = 21150;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901358, type, value FROM weenie_properties_float WHERE object_Id = 21150;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901358, type, value FROM weenie_properties_string WHERE object_Id = 21150;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901358, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21150;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901358, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21150;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901358, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21150;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901358, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21150;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901358, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21150;
DELETE FROM weenie_properties_string WHERE object_Id = 901358 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901358, 1, 'Wardenforged Sollerets');
DELETE FROM weenie_properties_string WHERE object_Id = 901358 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901358, 16, 'Pointed sabatons, gilded at the toe. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901358 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901358 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901358, 8, 117379928);
DELETE FROM weenie_properties_bool WHERE object_Id = 901358 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901358, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901358, 19, 15000);
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901358, 28, 540);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901358 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901358, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901358, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901358, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901358, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901358, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901358 AND type = 265; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901358, 265, 901);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901358, 3, 33493853);  -- part 3 -> 0x01ff135d
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901358, 4, 33493855);  -- part 4 -> 0x01ff135f
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901358, 7, 33493854);  -- part 7 -> 0x01ff135e
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901358, 8, 33493856);  -- part 8 -> 0x01ff1360

-- ---------------------------------------------------------------- THE SHIELD (not a set piece)
-- Clone of the Covenant Shield (21158). NO anim_part row (see the header): the held mesh 0x01FF1361
-- comes from RevivalGuard WardenforgedPlate, server property wardenforged_shield_part (default OFF).
-- Off, it is held as the Covenant Shield; dropped, it is ours either way (w901359.glb).
-- 901359 <- clone of 21158
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901359, 'ace901359-wardenforgedshield', type FROM weenie WHERE class_Id = 21158;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901359, type, value FROM weenie_properties_int WHERE object_Id = 21158;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901359, type, value FROM weenie_properties_int64 WHERE object_Id = 21158;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901359, type, value FROM weenie_properties_bool WHERE object_Id = 21158;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901359, type, value FROM weenie_properties_float WHERE object_Id = 21158;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901359, type, value FROM weenie_properties_string WHERE object_Id = 21158;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901359, type, value FROM weenie_properties_d_i_d WHERE object_Id = 21158;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901359, type, value FROM weenie_properties_i_i_d WHERE object_Id = 21158;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901359, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 21158;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901359, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 21158;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901359, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 21158;
DELETE FROM weenie_properties_string WHERE object_Id = 901359 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901359, 1, 'Wardenforged Shield');
DELETE FROM weenie_properties_string WHERE object_Id = 901359 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901359, 16, 'A heater shield of azure enamel with the Warden''s hex-sun in gold. Forged in the Empyrean Vault from the Forge-Warden''s own aetherium. The runes along its edges are the ward that bound the Warden to destroy anything touched by Shadow, and they still hold.');
DELETE FROM weenie_properties_string WHERE object_Id = 901359 AND type = 15;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901359 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901359, 8, 117379929);
DELETE FROM weenie_properties_bool WHERE object_Id = 901359 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901359, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901359 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901359, 19, 25000);
DELETE FROM weenie_properties_int WHERE object_Id = 901359 AND type = 28; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901359, 28, 420);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 13; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 13, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 14; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 14, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 15; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 15, 1.6);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 16; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 16, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 17; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 17, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 18; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 18, 1.2);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 19; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 19, 1.8);
DELETE FROM weenie_properties_float WHERE object_Id = 901359 AND type = 165; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (901359, 165, 1.0);
DELETE FROM weenie_properties_int WHERE object_Id = 901359 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901359, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901359 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901359, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901359 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901359, 160, 150);
DELETE FROM weenie_properties_int WHERE object_Id = 901359 AND type = 33; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901359, 33, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901359 AND type = 169;

-- ---------------------------------------------------------------- THE CLOAK (not a set piece)
-- Clone of the retail Cloak (44840): parts 29-33, so it costs no armour its look. Cosmetic: no
-- rolled proc (169, 320) and no magical outline (18).
-- 901360 <- clone of 44840
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901360, 'ace901360-wardenforgedcloak', type FROM weenie WHERE class_Id = 44840;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901360, type, value FROM weenie_properties_int WHERE object_Id = 44840;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901360, type, value FROM weenie_properties_int64 WHERE object_Id = 44840;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901360, type, value FROM weenie_properties_bool WHERE object_Id = 44840;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901360, type, value FROM weenie_properties_float WHERE object_Id = 44840;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901360, type, value FROM weenie_properties_string WHERE object_Id = 44840;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901360, type, value FROM weenie_properties_d_i_d WHERE object_Id = 44840;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901360, type, value FROM weenie_properties_i_i_d WHERE object_Id = 44840;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901360, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 44840;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901360, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 44840;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901360, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 44840;
DELETE FROM weenie_properties_string WHERE object_Id = 901360 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901360, 1, 'Wardenforged Cloak');
DELETE FROM weenie_properties_string WHERE object_Id = 901360 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901360, 16, 'An azure cloak edged in gold, the Forge-Warden''s hex-sun worked high on the back and an aetherium clasp at the throat.');
DELETE FROM weenie_properties_string WHERE object_Id = 901360 AND type = 15;
DELETE FROM weenie_properties_int WHERE object_Id = 901360 AND type = 169;
DELETE FROM weenie_properties_int WHERE object_Id = 901360 AND type = 320;
DELETE FROM weenie_properties_int WHERE object_Id = 901360 AND type = 18;
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 901360 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (901360, 8, 117379936);
DELETE FROM weenie_properties_bool WHERE object_Id = 901360 AND type = 84; INSERT INTO weenie_properties_bool (object_Id, type, value) VALUES (901360, 84, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901360 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901360, 19, 20000);
DELETE FROM weenie_properties_int WHERE object_Id = 901360 AND type = 158; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901360, 158, 7);
DELETE FROM weenie_properties_int WHERE object_Id = 901360 AND type = 159; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901360, 159, 1);
DELETE FROM weenie_properties_int WHERE object_Id = 901360 AND type = 160; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901360, 160, 150);
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901360, 29, 33493858);  -- part 29 -> 0x01ff1362
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901360, 30, 33493859);  -- part 30 -> 0x01ff1363
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901360, 31, 33493860);  -- part 31 -> 0x01ff1364
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901360, 32, 33493861);  -- part 32 -> 0x01ff1365
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) VALUES (901360, 33, 33493862);  -- part 33 -> 0x01ff1366

-- ---------------------------------------------------------------- THE WARDENFORGED INGOT (901361)
-- Clone of the retail Ingot (2438), its art and icon kept. Dropped by the Forge-Warden; the Chosen of
-- Asheron forges it, with three Radiant Golem Cores, into the next piece (wardenforged-source.sql).
-- 901361 <- clone of 2438
INSERT INTO weenie (class_Id, class_Name, type) SELECT 901361, 'ace901361-wardenforgedingot', type FROM weenie WHERE class_Id = 2438;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 901361, type, value FROM weenie_properties_int WHERE object_Id = 2438;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 901361, type, value FROM weenie_properties_int64 WHERE object_Id = 2438;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 901361, type, value FROM weenie_properties_bool WHERE object_Id = 2438;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 901361, type, value FROM weenie_properties_float WHERE object_Id = 2438;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 901361, type, value FROM weenie_properties_string WHERE object_Id = 2438;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 901361, type, value FROM weenie_properties_d_i_d WHERE object_Id = 2438;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 901361, type, value FROM weenie_properties_i_i_d WHERE object_Id = 2438;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 901361, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 2438;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 901361, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 2438;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 901361, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 2438;
INSERT INTO weenie_properties_spell_book (object_Id, spell, probability) SELECT 901361, spell, probability FROM weenie_properties_spell_book WHERE object_Id = 2438;
DELETE FROM weenie_properties_string WHERE object_Id = 901361 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901361, 1, 'Wardenforged Ingot');
DELETE FROM weenie_properties_string WHERE object_Id = 901361 AND type = 16; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (901361, 16, 'A bar of the Forge-Warden''s aetherium, still warm, the ward-runes crawling across it. The Chosen of Asheron at the Empyrean Vault''s mouth can forge it into Wardenforged plate, given three Radiant Golem Cores to temper it.');
DELETE FROM weenie_properties_string WHERE object_Id = 901361 AND type = 15;
DELETE FROM weenie_properties_int WHERE object_Id = 901361 AND type = 19; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901361, 19, 5000);
DELETE FROM weenie_properties_int WHERE object_Id = 901361 AND type = 5; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (901361, 5, 200);

-- Where it comes from: tools/gpubox-ace/wardenforged-source.sql (the Warden's drop, the Chosen's forging).

COMMIT;
