-- ZEFIR COMPANIONS, weenies 900750-900768. GENERATED by tools/gpubox-ace/gen_zefir_pets.py -- edit that, not this.
-- Re-runnable: deletes its own rows first. New rows only; nothing retail is changed.
START TRANSACTION;
DELETE FROM weenie_properties_int WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_int64 WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_bool WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_float WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_string WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_d_i_d WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_i_i_d WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_palette WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_texture_map WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_anim_part WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_attribute WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie_properties_attribute_2nd WHERE object_Id BETWEEN 900750 AND 900768;
DELETE FROM weenie WHERE class_Id BETWEEN 900750 AND 900768;

-- ---- Jibrit Zefir (looks like wcid 2608)
-- 900750 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900750, 'ace900750-petjibritzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900750, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900750, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900750, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900750, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900750, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900750, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900750, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900750, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900750, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900750, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900750, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900750, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900750 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900750, 1, 'Pet Jibrit Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900750 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900750, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900750 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900750, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900750 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900750, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900750 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900750, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900750 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900750, 7, 268435811);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900750 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900750, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900750 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900750, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900750 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900750, 3, 2);
DELETE FROM weenie_properties_int WHERE object_Id = 900750 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900750, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900750 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900750, 39, 0.6);

-- 900760 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900760, 'ace900760-jibritzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900760, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900760, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900760, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900760, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900760, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900760, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900760, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900760, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900760, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900760, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900760, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900760, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900760 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900760, 1, 'Jibrit Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900760 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900760, 14, 'Use this charm to call or dismiss your Pet Jibrit Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900760 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900760, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900760 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900760, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900760 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900760, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900760 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900760, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900760 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900760, 266, 900750);

-- ---- Kilif Zefir (looks like wcid 2610)
-- 900751 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900751, 'ace900751-petkilifzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900751, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900751, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900751, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900751, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900751, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900751, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900751, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900751, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900751, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900751, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900751, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900751, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900751 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900751, 1, 'Pet Kilif Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900751 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900751, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900751 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900751, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900751 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900751, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900751 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900751, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900751 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900751, 7, 268435811);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900751 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900751, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900751 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900751, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900751 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900751, 3, 8);
DELETE FROM weenie_properties_int WHERE object_Id = 900751 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900751, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900751 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900751, 39, 0.6);

-- 900761 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900761, 'ace900761-kilifzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900761, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900761, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900761, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900761, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900761, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900761, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900761, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900761, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900761, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900761, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900761, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900761, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900761 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900761, 1, 'Kilif Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900761 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900761, 14, 'Use this charm to call or dismiss your Pet Kilif Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900761 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900761, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900761 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900761, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900761 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900761, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900761 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900761, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900761 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900761, 266, 900751);

-- ---- Nalif Zefir (looks like wcid 7129)
-- 900752 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900752, 'ace900752-petnalifzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900752, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900752, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900752, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900752, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900752, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900752, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900752, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900752, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900752, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900752, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900752, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900752, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900752 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900752, 1, 'Pet Nalif Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900752 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900752, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900752 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900752, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900752 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900752, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900752 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900752, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900752 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900752, 7, 268435811);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900752 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900752, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900752 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900752, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900752 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900752, 3, 14);
DELETE FROM weenie_properties_int WHERE object_Id = 900752 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900752, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900752 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900752, 39, 0.6);

-- 900762 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900762, 'ace900762-nalifzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900762, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900762, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900762, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900762, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900762, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900762, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900762, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900762, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900762, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900762, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900762, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900762, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900762 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900762, 1, 'Nalif Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900762 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900762, 14, 'Use this charm to call or dismiss your Pet Nalif Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900762 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900762, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900762 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900762, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900762 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900762, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900762 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900762, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900762 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900762, 266, 900752);

-- ---- Sufut Zefir (looks like wcid 7128)
-- 900753 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900753, 'ace900753-petsufutzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900753, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900753, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900753, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900753, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900753, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900753, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900753, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900753, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900753, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900753, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900753, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900753, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900753 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900753, 1, 'Pet Sufut Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900753 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900753, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900753 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900753, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900753 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900753, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900753 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900753, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900753 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900753, 7, 268435811);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900753 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900753, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900753 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900753, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900753 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900753, 3, 19);
DELETE FROM weenie_properties_int WHERE object_Id = 900753 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900753, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900753 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900753, 39, 0.6);

-- 900763 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900763, 'ace900763-sufutzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900763, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900763, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900763, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900763, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900763, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900763, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900763, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900763, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900763, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900763, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900763, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900763, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900763 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900763, 1, 'Sufut Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900763 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900763, 14, 'Use this charm to call or dismiss your Pet Sufut Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900763 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900763, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900763 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900763, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900763 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900763, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900763 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900763, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900763 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900763, 266, 900753);

-- ---- Zofrit Zefir (looks like wcid 2611)
-- 900754 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900754, 'ace900754-petzofritzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900754, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900754, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900754, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900754, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900754, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900754, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900754, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900754, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900754, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900754, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900754, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900754, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900754 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900754, 1, 'Pet Zofrit Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900754 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900754, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900754 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900754, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900754 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900754, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900754 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900754, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900754 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900754, 7, 268435811);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900754 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900754, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900754 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900754, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900754 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900754, 3, 76);
DELETE FROM weenie_properties_int WHERE object_Id = 900754 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900754, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900754 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900754, 39, 0.6);

-- 900764 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900764, 'ace900764-zofritzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900764, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900764, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900764, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900764, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900764, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900764, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900764, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900764, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900764, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900764, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900764, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900764, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900764 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900764, 1, 'Zofrit Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900764 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900764, 14, 'Use this charm to call or dismiss your Pet Zofrit Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900764 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900764, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900764 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900764, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900764 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900764, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900764 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900764, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900764 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900764, 266, 900754);

-- ---- Dark Zefir (looks like wcid 25885)
-- 900755 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900755, 'ace900755-petdarkzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900755, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900755, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900755, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900755, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900755, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900755, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900755, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900755, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900755, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900755, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900755, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900755, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900755 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900755, 1, 'Pet Dark Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900755 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900755, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900755 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900755, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900755 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900755, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900755 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900755, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900755 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900755, 7, 268436729);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900755 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900755, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900755 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900755, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900755 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900755, 3, 2);
DELETE FROM weenie_properties_int WHERE object_Id = 900755 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900755, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900755 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900755, 39, 0.6);

-- 900765 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900765, 'ace900765-darkzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900765, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900765, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900765, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900765, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900765, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900765, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900765, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900765, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900765, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900765, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900765, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900765, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900765 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900765, 1, 'Dark Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900765 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900765, 14, 'Use this charm to call or dismiss your Pet Dark Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900765 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900765, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900765 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900765, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900765 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900765, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900765 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900765, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900765 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900765, 266, 900755);

-- ---- Dusk Zefir (looks like wcid 25886)
-- 900756 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900756, 'ace900756-petduskzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900756, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900756, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900756, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900756, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900756, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900756, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900756, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900756, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900756, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900756, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900756, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900756, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900756 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900756, 1, 'Pet Dusk Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900756 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900756, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900756 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900756, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900756 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900756, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900756 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900756, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900756 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900756, 7, 268436729);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900756 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900756, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900756 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900756, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900756 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900756, 3, 8);
DELETE FROM weenie_properties_int WHERE object_Id = 900756 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900756, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900756 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900756, 39, 0.6);

-- 900766 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900766, 'ace900766-duskzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900766, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900766, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900766, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900766, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900766, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900766, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900766, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900766, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900766, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900766, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900766, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900766, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900766 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900766, 1, 'Dusk Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900766 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900766, 14, 'Use this charm to call or dismiss your Pet Dusk Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900766 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900766, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900766 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900766, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900766 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900766, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900766 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900766, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900766 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900766, 266, 900756);

-- ---- Kirit Zefir (looks like wcid 31017)
-- 900757 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900757, 'ace900757-petkiritzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900757, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900757, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900757, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900757, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900757, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900757, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900757, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900757, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900757, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900757, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900757, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900757, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900757 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900757, 1, 'Pet Kirit Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900757 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900757, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900757 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900757, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900757 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900757, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900757 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900757, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900757 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900757, 7, 268436729);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900757 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900757, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900757 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900757, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900757 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900757, 3, 19);
DELETE FROM weenie_properties_int WHERE object_Id = 900757 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900757, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900757 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900757, 39, 0.6);

-- 900767 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900767, 'ace900767-kiritzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900767, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900767, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900767, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900767, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900767, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900767, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900767, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900767, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900767, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900767, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900767, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900767, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900767 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900767, 1, 'Kirit Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900767 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900767, 14, 'Use this charm to call or dismiss your Pet Kirit Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900767 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900767, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900767 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900767, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900767 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900767, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900767 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900767, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900767 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900767, 266, 900757);

-- ---- Infernal Zefir (looks like wcid 25887)
-- 900758 <- clone of 33922
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900758, 'ace900758-petinfernalzefir', type FROM weenie WHERE class_Id = 33922;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900758, type, value FROM weenie_properties_int WHERE object_Id = 33922;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900758, type, value FROM weenie_properties_int64 WHERE object_Id = 33922;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900758, type, value FROM weenie_properties_bool WHERE object_Id = 33922;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900758, type, value FROM weenie_properties_float WHERE object_Id = 33922;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900758, type, value FROM weenie_properties_string WHERE object_Id = 33922;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900758, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900758, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33922;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900758, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33922;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900758, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33922;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900758, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900758, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33922;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900758, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33922;
DELETE FROM weenie_properties_string WHERE object_Id = 900758 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900758, 1, 'Pet Infernal Zefir');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900758 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900758, 1, 33555610);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900758 AND type = 2; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900758, 2, 150995049);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900758 AND type = 3; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900758, 3, 536870975);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900758 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900758, 6, 67109305);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900758 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900758, 7, 268436729);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900758 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900758, 8, 100669123);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900758 AND type = 22; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900758, 22, 872415279);
DELETE FROM weenie_properties_int WHERE object_Id = 900758 AND type = 3; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900758, 3, 76);
DELETE FROM weenie_properties_int WHERE object_Id = 900758 AND type = 2; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900758, 2, 29);
DELETE FROM weenie_properties_float WHERE object_Id = 900758 AND type = 39; INSERT INTO weenie_properties_float (object_Id, type, value) VALUES (900758, 39, 0.6);

-- 900768 <- clone of 33925
INSERT INTO weenie (class_Id, class_Name, type) SELECT 900768, 'ace900768-infernalzefircharm', type FROM weenie WHERE class_Id = 33925;
INSERT INTO weenie_properties_int (object_Id, type, value) SELECT 900768, type, value FROM weenie_properties_int WHERE object_Id = 33925;
INSERT INTO weenie_properties_int64 (object_Id, type, value) SELECT 900768, type, value FROM weenie_properties_int64 WHERE object_Id = 33925;
INSERT INTO weenie_properties_bool (object_Id, type, value) SELECT 900768, type, value FROM weenie_properties_bool WHERE object_Id = 33925;
INSERT INTO weenie_properties_float (object_Id, type, value) SELECT 900768, type, value FROM weenie_properties_float WHERE object_Id = 33925;
INSERT INTO weenie_properties_string (object_Id, type, value) SELECT 900768, type, value FROM weenie_properties_string WHERE object_Id = 33925;
INSERT INTO weenie_properties_d_i_d (object_Id, type, value) SELECT 900768, type, value FROM weenie_properties_d_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_i_i_d (object_Id, type, value) SELECT 900768, type, value FROM weenie_properties_i_i_d WHERE object_Id = 33925;
INSERT INTO weenie_properties_palette (object_Id, sub_Palette_Id, offset, length) SELECT 900768, sub_Palette_Id, offset, length FROM weenie_properties_palette WHERE object_Id = 33925;
INSERT INTO weenie_properties_texture_map (object_Id, `index`, old_Id, new_Id) SELECT 900768, `index`, old_Id, new_Id FROM weenie_properties_texture_map WHERE object_Id = 33925;
INSERT INTO weenie_properties_anim_part (object_Id, `index`, animation_Id) SELECT 900768, `index`, animation_Id FROM weenie_properties_anim_part WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute (object_Id, type, init_Level, level_From_C_P, c_P_Spent) SELECT 900768, type, init_Level, level_From_C_P, c_P_Spent FROM weenie_properties_attribute WHERE object_Id = 33925;
INSERT INTO weenie_properties_attribute_2nd (object_Id, type, init_Level, level_From_C_P, c_P_Spent, current_Level) SELECT 900768, type, init_Level, level_From_C_P, c_P_Spent, current_Level FROM weenie_properties_attribute_2nd WHERE object_Id = 33925;
DELETE FROM weenie_properties_string WHERE object_Id = 900768 AND type = 1; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900768, 1, 'Infernal Zefir Charm');
DELETE FROM weenie_properties_string WHERE object_Id = 900768 AND type = 14; INSERT INTO weenie_properties_string (object_Id, type, value) VALUES (900768, 14, 'Use this charm to call or dismiss your Pet Infernal Zefir.');
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900768 AND type = 1; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900768, 1, 33554809);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900768 AND type = 6; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900768, 6, 67111919);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900768 AND type = 7; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900768, 7, 268435723);
DELETE FROM weenie_properties_d_i_d WHERE object_Id = 900768 AND type = 8; INSERT INTO weenie_properties_d_i_d (object_Id, type, value) VALUES (900768, 8, 100686697);
DELETE FROM weenie_properties_int WHERE object_Id = 900768 AND type = 266; INSERT INTO weenie_properties_int (object_Id, type, value) VALUES (900768, 266, 900758);

COMMIT;
